-- Buff and debuff duration overrides for Arknights: Endfield.
-- Run this file in the Supabase SQL editor after operator_skills has been populated.

create table if not exists public.effect_duration_overrides (
    id bigint generated by default as identity primary key,
    game text not null default 'arknights_endfield',
    operator_id bigint not null references public.operators(id) on delete cascade,
    operator_name text not null,
    skill_id bigint not null references public.operator_skills(id) on delete cascade,
    skill_name text not null,
    effect_type text not null check (effect_type in ('buff', 'debuff')),
    effect_key text not null,
    effect_name text not null,
    duration_seconds numeric not null check (duration_seconds > 0),
    verified boolean not null default false,
    source_url text,
    source_note text,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now()
);

create unique index if not exists effect_duration_overrides_unique_effect
    on public.effect_duration_overrides (game, skill_id, effect_type, effect_key);

create index if not exists effect_duration_overrides_operator_skill_idx
    on public.effect_duration_overrides (game, operator_id, skill_id);

alter table public.effect_duration_overrides enable row level security;

drop policy if exists "effect duration overrides are publicly readable" on public.effect_duration_overrides;
create policy "effect duration overrides are publicly readable"
    on public.effect_duration_overrides
    for select
    using (true);

create table if not exists public.effect_duration_research_queue (
    id bigint generated by default as identity primary key,
    game text not null default 'arknights_endfield',
    operator_id bigint not null references public.operators(id) on delete cascade,
    operator_name text not null,
    skill_id bigint not null references public.operator_skills(id) on delete cascade,
    skill_name text not null,
    effect_type text not null check (effect_type in ('buff', 'debuff')),
    effect_key text not null,
    effect_name text not null,
    candidate_duration_seconds numeric,
    status text not null default 'missing' check (status in ('missing', 'researching', 'verified', 'ignored')),
    priority integer not null default 50,
    source_url text,
    source_note text,
    notes text,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now()
);

create unique index if not exists effect_duration_research_queue_unique_effect
    on public.effect_duration_research_queue (game, skill_id, effect_type, effect_key);

create index if not exists effect_duration_research_queue_status_idx
    on public.effect_duration_research_queue (game, status, priority);

alter table public.effect_duration_research_queue enable row level security;

drop policy if exists "effect duration research queue is publicly readable" on public.effect_duration_research_queue;
create policy "effect duration research queue is publicly readable"
    on public.effect_duration_research_queue
    for select
    using (true);

create or replace view public.effect_duration_candidates as
with direct_buffs as (
    select
        op.id as operator_id,
        op.name as operator_name,
        skill.id as skill_id,
        skill.name as skill_name,
        'buff'::text as effect_type,
        effect_data.value as effect_data,
        'direct buff'::text as source_note
    from public.operator_skills skill
    join public.operators op on op.id = skill.operator_id
    cross join lateral jsonb_array_elements(
        case
            when jsonb_typeof(skill.raw_data::jsonb->'buffs') = 'array'
                then skill.raw_data::jsonb->'buffs'
            else '[]'::jsonb
        end
    ) as effect_data
),
direct_debuffs as (
    select
        op.id as operator_id,
        op.name as operator_name,
        skill.id as skill_id,
        skill.name as skill_name,
        'debuff'::text as effect_type,
        effect_data.value as effect_data,
        'direct debuff'::text as source_note
    from public.operator_skills skill
    join public.operators op on op.id = skill.operator_id
    cross join lateral jsonb_array_elements(
        case
            when jsonb_typeof(skill.raw_data::jsonb->'debuffs') = 'array'
                then skill.raw_data::jsonb->'debuffs'
            else '[]'::jsonb
        end
    ) as effect_data
),
conditional_buffs as (
    select
        op.id as operator_id,
        op.name as operator_name,
        skill.id as skill_id,
        skill.name as skill_name,
        'buff'::text as effect_type,
        effect_data.value as effect_data,
        'conditional buff'::text as source_note
    from public.operator_skills skill
    join public.operators op on op.id = skill.operator_id
    cross join lateral jsonb_array_elements(
        case
            when jsonb_typeof(skill.raw_data::jsonb->'conditionalBuffs') = 'array'
                then skill.raw_data::jsonb->'conditionalBuffs'
            else '[]'::jsonb
        end
    ) as condition_data
    cross join lateral jsonb_array_elements(
        case
            when jsonb_typeof(condition_data.value->'buffs') = 'array'
                then condition_data.value->'buffs'
            else '[]'::jsonb
        end
    ) as effect_data
),
conditional_debuffs as (
    select
        op.id as operator_id,
        op.name as operator_name,
        skill.id as skill_id,
        skill.name as skill_name,
        'debuff'::text as effect_type,
        effect_data.value as effect_data,
        'conditional debuff'::text as source_note
    from public.operator_skills skill
    join public.operators op on op.id = skill.operator_id
    cross join lateral jsonb_array_elements(
        case
            when jsonb_typeof(skill.raw_data::jsonb->'conditionalDebuffs') = 'array'
                then skill.raw_data::jsonb->'conditionalDebuffs'
            else '[]'::jsonb
        end
    ) as condition_data
    cross join lateral jsonb_array_elements(
        case
            when jsonb_typeof(condition_data.value->'debuffs') = 'array'
                then condition_data.value->'debuffs'
            else '[]'::jsonb
        end
    ) as effect_data
),
combined as (
    select * from direct_buffs
    union all
    select * from direct_debuffs
    union all
    select * from conditional_buffs
    union all
    select * from conditional_debuffs
)
select
    'arknights_endfield'::text as game,
    operator_id,
    operator_name,
    skill_id,
    skill_name,
    effect_type,
    nullif(
        trim(both '_' from regexp_replace(
            lower(trim(coalesce(
                effect_data->>'id',
                effect_data->>'appliesEffect',
                effect_data->>'effect',
                effect_data->>'key',
                effect_data->>'name',
                ''
            ))),
            '[^a-z0-9]+',
            '_',
            'g'
        )),
        ''
    ) as effect_key,
    coalesce(
        effect_data->>'name',
        effect_data->>'appliesEffect',
        effect_data->>'effect',
        effect_data->>'key',
        effect_data->>'id',
        'Unknown effect'
    ) as effect_name,
    case
        when (effect_data->>'durationSeconds') ~ '^[0-9]+(\.[0-9]+)?$'
            then (effect_data->>'durationSeconds')::numeric
        else null
    end as duration_seconds,
    source_note
from combined
where effect_data is not null;

insert into public.effect_duration_overrides (
    game,
    operator_id,
    operator_name,
    skill_id,
    skill_name,
    effect_type,
    effect_key,
    effect_name,
    duration_seconds,
    verified,
    source_note
)
select distinct
    candidate.game,
    candidate.operator_id,
    candidate.operator_name,
    candidate.skill_id,
    candidate.skill_name,
    candidate.effect_type,
    candidate.effect_key,
    candidate.effect_name,
    candidate.duration_seconds,
    false,
    candidate.source_note || ' from operator_skills.raw_data'
from public.effect_duration_candidates candidate
where candidate.effect_key is not null
  and candidate.duration_seconds is not null
  and candidate.duration_seconds > 0
on conflict (game, skill_id, effect_type, effect_key) do update
set
    operator_name = excluded.operator_name,
    skill_name = excluded.skill_name,
    effect_name = excluded.effect_name,
    duration_seconds = case
        when public.effect_duration_overrides.verified then public.effect_duration_overrides.duration_seconds
        else excluded.duration_seconds
    end,
    source_note = case
        when public.effect_duration_overrides.verified then public.effect_duration_overrides.source_note
        else excluded.source_note
    end,
    updated_at = now();

insert into public.effect_duration_research_queue (
    game,
    operator_id,
    operator_name,
    skill_id,
    skill_name,
    effect_type,
    effect_key,
    effect_name,
    candidate_duration_seconds,
    status,
    priority,
    source_note
)
select distinct
    candidate.game,
    candidate.operator_id,
    candidate.operator_name,
    candidate.skill_id,
    candidate.skill_name,
    candidate.effect_type,
    candidate.effect_key,
    candidate.effect_name,
    candidate.duration_seconds,
    case
        when candidate.duration_seconds is null then 'missing'
        else 'verified'
    end,
    case
        when candidate.duration_seconds is null then 20
        else 80
    end,
    candidate.source_note
from public.effect_duration_candidates candidate
where candidate.effect_key is not null
  and not exists (
      select 1
      from public.effect_duration_overrides override
      where override.game = candidate.game
        and override.skill_id = candidate.skill_id
        and override.effect_type = candidate.effect_type
        and override.effect_key = candidate.effect_key
  )
on conflict (game, skill_id, effect_type, effect_key) do update
set
    operator_name = excluded.operator_name,
    skill_name = excluded.skill_name,
    effect_name = excluded.effect_name,
    candidate_duration_seconds = excluded.candidate_duration_seconds,
    source_note = excluded.source_note,
    updated_at = now();

-- Google Sheets export query:
-- select priority,status,operator_name,skill_name,effect_type,effect_key,effect_name,candidate_duration_seconds,source_url,source_note,notes
-- from public.effect_duration_research_queue
-- order by priority asc, operator_name asc, skill_name asc, effect_type asc, effect_name asc;
