-- Complete Arknights: Endfield gear catalog seed for Supabase.
-- Generated from Icy Veins gear pages on 2026-05-31.
-- Source index: https://www.icy-veins.com/arknights-endfield/gear
-- Run supabase/schema.sql first. This file is safe to rerun.
--
-- Important for Supabase:
--   Run the complete file from "begin;" down to "commit;".
--   Do not select only the value rows. If Supabase reports "LINE 1: ('some_gear_key'...)",
--   then only a row fragment was executed instead of the full insert statement.
--
-- Slot mapping for this app:
--   Armor -> gear_slot = 'body'
--   Gloves -> gear_slot = 'hands'
--   Kit items -> gear_slot = 'kit' and can be equipped in Kit 1 or Kit 2.
--
-- Rarity note:
--   Source pages use gear tiers. This seed maps source tier + 1 into the app's 1-6 rarity scale.
--   Example: source Tier 4 becomes rarity 5, which uses the gold frame in the editor.

begin;

alter table public.gear_pieces drop constraint if exists gear_pieces_gear_slot_check;

alter table public.gear_pieces
    add constraint gear_pieces_gear_slot_check
    check (gear_slot in ('body', 'hands', 'kit', 'kit1', 'kit2'));

insert into public.gear_pieces (
    gear_key,
    game,
    name,
    gear_slot,
    set_name,
    rarity,
    icon_path,
    main_attribute,
    secondary_attribute,
    passive_name,
    sort_order
) values
    ('bonekrusha_heavy_armor', 'arknights_endfield', 'Bonekrusha Heavy Armor', 'body', 'Bonekrusha', 5, 'assets/gear/bonekrusha_heavy_armor.png', 'Agility +87', 'Defense +56; Intellect +58; Ultimate Gain Efficiency +12.3%', 'Bonekrusha 3-piece set effect', 1000),
    ('bonekrusha_heavy_armor_t1', 'arknights_endfield', 'Bonekrusha Heavy Armor T1', 'body', 'Bonekrusha', 5, 'assets/gear/bonekrusha_heavy_armor_t1.png', 'Agility +87', 'Defense +56; Strength +58; Combo Skill DMG Bonus +20.7%', 'Bonekrusha 3-piece set effect', 1001),
    ('bonekrusha_poncho', 'arknights_endfield', 'Bonekrusha Poncho', 'body', 'Bonekrusha', 5, 'assets/gear/bonekrusha_poncho.png', 'Will +87', 'Defense +56; Strength +58; Combo Skill DMG Bonus +20.7%', 'Bonekrusha 3-piece set effect', 1002),
    ('bonekrusha_poncho_t1', 'arknights_endfield', 'Bonekrusha Poncho T1', 'body', 'Bonekrusha', 5, 'assets/gear/bonekrusha_poncho_t1.png', 'Will +87', 'Defense +56; Agility +58; Ultimate Gain Efficiency +12.3%', 'Bonekrusha 3-piece set effect', 1003),
    ('bonekrusha_wristband', 'arknights_endfield', 'Bonekrusha Wristband', 'hands', 'Bonekrusha', 5, 'assets/gear/bonekrusha_wristband.png', 'Strength +65', 'Defense +42; Agility +43; Heat and Nature DMG Dealt Bonus +19.2%', 'Bonekrusha 3-piece set effect', 1004),
    ('bonekrusha_wristband_t1', 'arknights_endfield', 'Bonekrusha Wristband T1', 'hands', 'Bonekrusha', 5, 'assets/gear/bonekrusha_wristband_t1.png', 'Agility +65', 'Defense +42; Strength +43; Cryo and Electric DMG Dealt Bonus +19.2%', 'Bonekrusha 3-piece set effect', 1005),
    ('bonekrusha_figurine', 'arknights_endfield', 'Bonekrusha Figurine', 'kit', 'Bonekrusha', 5, 'assets/gear/bonekrusha_figurine.png', 'Will +32', 'Defense +21; Agility +21; Battle Skill DMG Bonus +41.4%', 'Bonekrusha 3-piece set effect', 1006),
    ('bonekrusha_mask', 'arknights_endfield', 'Bonekrusha Mask', 'kit', 'Bonekrusha', 5, 'assets/gear/bonekrusha_mask.png', 'Agility +32', 'Defense +21; Strength +21; DMG Bonus vs. Staggered +41.4%', 'Bonekrusha 3-piece set effect', 1007),
    ('bonekrusha_mask_t1', 'arknights_endfield', 'Bonekrusha Mask T1', 'kit', 'Bonekrusha', 5, 'assets/gear/bonekrusha_mask_t1.png', 'Agility +32', 'Defense +21; Strength +21; Crit Rate +10.4%', 'Bonekrusha 3-piece set effect', 1008),
    ('bonekrusha_figurine_t1', 'arknights_endfield', 'Bonekrusha Figurine T1', 'kit', 'Bonekrusha', 5, 'assets/gear/bonekrusha_figurine_t1.png', 'Will +32', 'Defense +21; Intellect +21; Combo Skill DMG Bonus +41.4%', 'Bonekrusha 3-piece set effect', 1009),
    ('bonekrusha_mask_t2', 'arknights_endfield', 'Bonekrusha Mask T2', 'kit', 'Bonekrusha', 5, 'assets/gear/bonekrusha_mask_t2.png', 'Agility +32', 'Defense +21; Strength +21; Battle Skill DMG Bonus +41.4%', 'Bonekrusha 3-piece set effect', 1010),
    ('bonekrusha_heavy_armor_t2', 'arknights_endfield', 'Bonekrusha Heavy Armor T2', 'body', 'Bonekrusha', 5, 'assets/gear/bonekrusha_heavy_armor_t2.png', 'Agility +87', 'Defense +56; Strength +58; Cryo and Electric DMG Dealt Bonus +11.5%', 'Bonekrusha 3-piece set effect', 1011),
    ('bonekrusha_gloves', 'arknights_endfield', 'Bonekrusha Gloves', 'hands', 'Bonekrusha', 5, 'assets/gear/bonekrusha_gloves.png', 'Will +65', 'Defense +42; Agility +43; Cryo and Electric DMG Dealt Bonus +19.2%', 'Bonekrusha 3-piece set effect', 1012),
    ('bonekrusha_figurine_t2', 'arknights_endfield', 'Bonekrusha Figurine T2', 'kit', 'Bonekrusha', 5, 'assets/gear/bonekrusha_figurine_t2.png', 'Will +32', 'Defense +21; Intellect +21; Battle Skill DMG Bonus +41.4%', 'Bonekrusha 3-piece set effect', 1013),
    ('eternal_xiranite_armor', 'arknights_endfield', 'Eternal Xiranite Armor', 'body', 'Eternal Xiranite', 5, 'assets/gear/eternal_xiranite_armor.png', 'Will +87', 'Defense +56; Intellect +58; Arts Intensity +20', 'Eternal Xiranite 3-piece set effect', 1014),
    ('eternal_xiranite_gloves', 'arknights_endfield', 'Eternal Xiranite Gloves', 'hands', 'Eternal Xiranite', 5, 'assets/gear/eternal_xiranite_gloves.png', 'Intellect +65', 'Defense +42; Strength +43; Ultimate Gain Efficiency +20.5%', 'Eternal Xiranite 3-piece set effect', 1015),
    ('eternal_xiranite_gloves_t1', 'arknights_endfield', 'Eternal Xiranite Gloves T1', 'hands', 'Eternal Xiranite', 5, 'assets/gear/eternal_xiranite_gloves_t1.png', 'Intellect +65', 'Defense +42; Will +43; Ultimate Gain Efficiency +20.5%', 'Eternal Xiranite 3-piece set effect', 1016),
    ('eternal_xiranite_power_core', 'arknights_endfield', 'Eternal Xiranite Power Core', 'kit', 'Eternal Xiranite', 5, 'assets/gear/eternal_xiranite_power_core.png', 'Intellect +32', 'Defense +21; Strength +21; Ultimate Gain Efficiency +24.6%', 'Eternal Xiranite 3-piece set effect', 1017),
    ('eternal_xiranite_power_core_t1', 'arknights_endfield', 'Eternal Xiranite Power Core T1', 'kit', 'Eternal Xiranite', 5, 'assets/gear/eternal_xiranite_power_core_t1.png', 'Intellect +32', 'Defense +21; Will +21; Treatment Bonus +20.7%', 'Eternal Xiranite 3-piece set effect', 1018),
    ('eternal_xiranite_auxiliary_arm', 'arknights_endfield', 'Eternal Xiranite Auxiliary Arm', 'kit', 'Eternal Xiranite', 5, 'assets/gear/eternal_xiranite_auxiliary_arm.png', 'Will +32', 'Defense +21; Intellect +21; Ultimate Gain Efficiency +24.6%', 'Eternal Xiranite 3-piece set effect', 1019),
    ('frontiers_armor', 'arknights_endfield', 'Frontiers Armor', 'body', 'Frontiers', 5, 'assets/gear/frontiers_armor.png', 'Strength +87', 'Defense +56; Intellect +58; Ultimate DMG Bonus +25.9%', 'Frontiers 3-piece set effect', 1020),
    ('frontiers_armor_t1', 'arknights_endfield', 'Frontiers Armor T1', 'body', 'Frontiers', 5, 'assets/gear/frontiers_armor_t1.png', 'Strength +87', 'Defense +56; Agility +58; Battle Skill DMG Bonus +20.7%', 'Frontiers 3-piece set effect', 1021),
    ('frontiers_armor_t2', 'arknights_endfield', 'Frontiers Armor T2', 'body', 'Frontiers', 5, 'assets/gear/frontiers_armor_t2.png', 'Agility +87', 'Defense +56; Intellect +58; Battle Skill DMG Bonus +20.7%', 'Frontiers 3-piece set effect', 1022),
    ('frontiers_armor_t3', 'arknights_endfield', 'Frontiers Armor T3', 'body', 'Frontiers', 5, 'assets/gear/frontiers_armor_t3.png', 'Agility +87', 'Defense +56; Intellect +58; Secondary Attribute +10.4%', 'Frontiers 3-piece set effect', 1023),
    ('frontiers_protection_suit', 'arknights_endfield', 'Frontiers Protection Suit', 'body', 'Frontiers', 5, 'assets/gear/frontiers_protection_suit.png', 'Intellect +87', 'Defense +56; Agility +58; Ultimate Gain Efficiency +12.3%', 'Frontiers 3-piece set effect', 1024),
    ('frontiers_blight_res_gloves', 'arknights_endfield', 'Frontiers Blight RES Gloves', 'hands', 'Frontiers', 5, 'assets/gear/frontiers_blight_res_gloves.png', 'Agility +65', 'Defense +42; Intellect +43; Battle Skill DMG Bonus +34.5%', 'Frontiers 3-piece set effect', 1025),
    ('frontiers_fiber_gloves', 'arknights_endfield', 'Frontiers Fiber Gloves', 'hands', 'Frontiers', 5, 'assets/gear/frontiers_fiber_gloves.png', 'Will +65', 'Defense +42; Strength +43; All Skill DMG Bonus +23%', 'Frontiers 3-piece set effect', 1026),
    ('frontiers_comm', 'arknights_endfield', 'Frontiers Comm', 'kit', 'Frontiers', 5, 'assets/gear/frontiers_comm.png', 'Strength +32', 'Defense +21; Agility +21; Combo Skill DMG Bonus +41.4%', 'Frontiers 3-piece set effect', 1027),
    ('frontiers_comm_t1', 'arknights_endfield', 'Frontiers Comm T1', 'kit', 'Frontiers', 5, 'assets/gear/frontiers_comm_t1.png', 'Strength +32', 'Defense +21; Intellect +21; Cryo and Electric DMG Dealt Bonus +23%', 'Frontiers 3-piece set effect', 1028),
    ('frontiers_analyzer', 'arknights_endfield', 'Frontiers Analyzer', 'kit', 'Frontiers', 5, 'assets/gear/frontiers_analyzer.png', 'Strength +41', 'Defense +21; Ultimate DMG Bonus +51.7%', 'Frontiers 3-piece set effect', 1029),
    ('frontiers_extra_o2_tube', 'arknights_endfield', 'Frontiers Extra O2 Tube', 'kit', 'Frontiers', 5, 'assets/gear/frontiers_extra_o2_tube.png', 'Agility +32', 'Defense +21; Intellect +21; Secondary Attribute +20.7%', 'Frontiers 3-piece set effect', 1030),
    ('frontiers_o2_tube', 'arknights_endfield', 'Frontiers O2 Tube', 'kit', 'Frontiers', 5, 'assets/gear/frontiers_o2_tube.png', 'Will +41', 'Defense +21; Physical DMG Bonus +23%', 'Frontiers 3-piece set effect', 1031),
    ('frontiers_fiber_gloves_t1', 'arknights_endfield', 'Frontiers Fiber Gloves T1', 'hands', 'Frontiers', 5, 'assets/gear/frontiers_fiber_gloves_t1.png', 'Intellect +65', 'Defense +42; Agility +43; Ultimate Gain Efficiency +20.5%', 'Frontiers 3-piece set effect', 1032),
    ('frontiers_extra_o2_tube_t1', 'arknights_endfield', 'Frontiers Extra O2 Tube T1', 'kit', 'Frontiers', 5, 'assets/gear/frontiers_extra_o2_tube_t1.png', 'Intellect +32', 'Defense +21; Agility +21; Secondary Attribute +20.7%', 'Frontiers 3-piece set effect', 1033),
    ('hot_work_exoskeleton', 'arknights_endfield', 'Hot Work Exoskeleton', 'body', 'Hot Work', 5, 'assets/gear/hot_work_exoskeleton.png', 'Strength +87', 'Defense +56; Agility +58; Heat and Nature DMG Dealt Bonus +11.5%', 'Hot Work 3-piece set effect', 1034),
    ('hot_work_exo_rig', 'arknights_endfield', 'Hot Work Exo-Rig', 'body', 'Hot Work', 5, 'assets/gear/hot_work_exo_rig.png', 'Intellect +87', 'Defense +56; Will +58; Heat and Nature DMG Dealt Bonus +11.5%', 'Hot Work 3-piece set effect', 1035),
    ('hot_work_gloves', 'arknights_endfield', 'Hot Work Gloves', 'hands', 'Hot Work', 5, 'assets/gear/hot_work_gloves.png', 'Strength +65', 'Defense +42; Will +43; Arts Intensity +34', 'Hot Work 3-piece set effect', 1036),
    ('hot_work_gauntlets', 'arknights_endfield', 'Hot Work Gauntlets', 'hands', 'Hot Work', 5, 'assets/gear/hot_work_gauntlets.png', 'Intellect +65', 'Defense +42; Strength +43; Heat and Nature DMG Dealt Bonus +19.2%', 'Hot Work 3-piece set effect', 1037),
    ('hot_work_gauntlets_t1', 'arknights_endfield', 'Hot Work Gauntlets T1', 'hands', 'Hot Work', 5, 'assets/gear/hot_work_gauntlets_t1.png', 'Will +65', 'Defense +42; Intellect +43; Heat and Nature DMG Dealt Bonus +19.2%', 'Hot Work 3-piece set effect', 1038),
    ('hot_work_power_bank', 'arknights_endfield', 'Hot Work Power Bank', 'kit', 'Hot Work', 5, 'assets/gear/hot_work_power_bank.png', 'Strength +32', 'Defense +21; Agility +21; Arts Intensity +41', 'Hot Work 3-piece set effect', 1039),
    ('hot_work_pyrometer', 'arknights_endfield', 'Hot Work Pyrometer', 'kit', 'Hot Work', 5, 'assets/gear/hot_work_pyrometer.png', 'Intellect +41', 'Defense +21; Battle Skill DMG Bonus +41.4%', 'Hot Work 3-piece set effect', 1040),
    ('hot_work_power_cartridge', 'arknights_endfield', 'Hot Work Power Cartridge', 'kit', 'Hot Work', 5, 'assets/gear/hot_work_power_cartridge.png', 'Will +32', 'Defense +21; Intellect +21; Arts Intensity +41', 'Hot Work 3-piece set effect', 1041),
    ('lynx_heavy_armor', 'arknights_endfield', 'LYNX Heavy Armor', 'body', 'LYNX', 5, 'assets/gear/lynx_heavy_armor.png', 'Strength +87', 'Defense +56; Will +58; Treatment Bonus +10.4%', 'LYNX 3-piece set effect', 1042),
    ('lynx_cuirass', 'arknights_endfield', 'LYNX Cuirass', 'body', 'LYNX', 5, 'assets/gear/lynx_cuirass.png', 'Will +87', 'Defense +56; Intellect +58; Treatment Bonus +10.4%', 'LYNX 3-piece set effect', 1043),
    ('lynx_gloves', 'arknights_endfield', 'LYNX Gloves', 'hands', 'LYNX', 5, 'assets/gear/lynx_gloves.png', 'Strength +65', 'Defense +42; Will +43; Ultimate Gain Efficiency +20.5%', 'LYNX 3-piece set effect', 1044),
    ('lynx_gauntlets', 'arknights_endfield', 'LYNX Gauntlets', 'hands', 'LYNX', 5, 'assets/gear/lynx_gauntlets.png', 'Will +65', 'Defense +42; Strength +43; Treatment Bonus +17.3%', 'LYNX 3-piece set effect', 1045),
    ('lynx_connector', 'arknights_endfield', 'LYNX Connector', 'kit', 'LYNX', 5, 'assets/gear/lynx_connector.png', 'Strength +32', 'Defense +21; Will +21; Final DMG Reduction +17.1%', 'LYNX 3-piece set effect', 1046),
    ('lynx_connector_t2', 'arknights_endfield', 'LYNX Connector T2', 'kit', 'LYNX', 5, 'assets/gear/lynx_connector_t2.png', 'Strength +41', 'Defense +21; HP +41.4%', 'LYNX 3-piece set effect', 1047),
    ('lynx_slab', 'arknights_endfield', 'LYNX Slab', 'kit', 'LYNX', 5, 'assets/gear/lynx_slab.png', 'Will +32', 'Defense +21; Intellect +21; Main Attribute +20.7%', 'LYNX 3-piece set effect', 1048),
    ('lynx_aegis_injector', 'arknights_endfield', 'LYNX Aegis Injector', 'kit', 'LYNX', 5, 'assets/gear/lynx_aegis_injector.png', 'Will +41', 'Defense +21; Treatment Bonus +20.7%', 'LYNX 3-piece set effect', 1049),
    ('lynx_connector_t1', 'arknights_endfield', 'LYNX Connector T1', 'kit', 'LYNX', 5, 'assets/gear/lynx_connector_t1.png', 'Strength +32', 'Defense +21; Will +21; HP +41.4%', 'LYNX 3-piece set effect', 1050),
    ('mi_security_armor', 'arknights_endfield', 'MI Security Armor', 'body', 'MI Security', 5, 'assets/gear/mi_security_armor.png', 'Agility +87', 'Defense +56; Strength +58; Arts Intensity +20', 'MI Security 3-piece set effect', 1051),
    ('mi_security_overalls', 'arknights_endfield', 'MI Security Overalls', 'body', 'MI Security', 5, 'assets/gear/mi_security_overalls.png', 'Intellect +87', 'Defense +56; Agility +58; Basic Attack DMG Bonus +13.8%', 'MI Security 3-piece set effect', 1052),
    ('mi_security_overalls_t1', 'arknights_endfield', 'MI Security Overalls T1', 'body', 'MI Security', 5, 'assets/gear/mi_security_overalls_t1.png', 'Intellect +87', 'Defense +56; Will +58; Crit Rate +5.2%', 'MI Security 3-piece set effect', 1053),
    ('mi_security_overalls_t2', 'arknights_endfield', 'MI Security Overalls T2', 'body', 'MI Security', 5, 'assets/gear/mi_security_overalls_t2.png', 'Will +87', 'Defense +56; Agility +58; Battle Skill DMG Bonus +20.7%', 'MI Security 3-piece set effect', 1054),
    ('mi_security_gloves', 'arknights_endfield', 'MI Security Gloves', 'hands', 'MI Security', 5, 'assets/gear/mi_security_gloves.png', 'Agility +65', 'Defense +42; Strength +43; Battle Skill DMG Bonus +34.5%', 'MI Security 3-piece set effect', 1055),
    ('mi_security_hands_ppe', 'arknights_endfield', 'MI Security Hands PPE', 'hands', 'MI Security', 5, 'assets/gear/mi_security_hands_ppe.png', 'Intellect +65', 'Defense +42; Agility +43; Basic Attack DMG Bonus +23%', 'MI Security 3-piece set effect', 1056),
    ('mi_security_hands_ppe_t1', 'arknights_endfield', 'MI Security Hands PPE T1', 'hands', 'MI Security', 5, 'assets/gear/mi_security_hands_ppe_t1.png', 'Intellect +65', 'Defense +42; Will +43; Crit Rate +8.6%', 'MI Security 3-piece set effect', 1057),
    ('mi_security_armband', 'arknights_endfield', 'MI Security Armband', 'kit', 'MI Security', 5, 'assets/gear/mi_security_armband.png', 'Strength +32', 'Defense +21; Will +21; Cryo and Electric DMG Dealt Bonus +23%', 'MI Security 3-piece set effect', 1058),
    ('mi_security_scope', 'arknights_endfield', 'MI Security Scope', 'kit', 'MI Security', 5, 'assets/gear/mi_security_scope.png', 'Agility +32', 'Defense +21; Strength +21; Battle Skill DMG Bonus +41.4%', 'MI Security 3-piece set effect', 1059),
    ('mi_security_toolkit', 'arknights_endfield', 'MI Security Toolkit', 'kit', 'MI Security', 5, 'assets/gear/mi_security_toolkit.png', 'Intellect +32', 'Defense +21; Agility +21; Crit Rate +10.4%', 'MI Security 3-piece set effect', 1060),
    ('mi_security_push_knife', 'arknights_endfield', 'MI Security Push Knife', 'kit', 'MI Security', 5, 'assets/gear/mi_security_push_knife.png', 'Will +32', 'Defense +21; Intellect +21; Heat and Nature DMG Dealt Bonus +23%', 'MI Security 3-piece set effect', 1061),
    ('mi_security_push_knife_t1', 'arknights_endfield', 'MI Security Push Knife T1', 'kit', 'MI Security', 5, 'assets/gear/mi_security_push_knife_t1.png', 'Will +32', 'Defense +21; Agility +21; Battle Skill DMG Bonus +41.4%', 'MI Security 3-piece set effect', 1062),
    ('mi_security_armor_t1', 'arknights_endfield', 'MI Security Armor T1', 'body', 'MI Security', 5, 'assets/gear/mi_security_armor_t1.png', 'Agility +87', 'Defense +56; Intellect +58; Ultimate Gain Efficiency +12.3%', 'MI Security 3-piece set effect', 1063),
    ('mi_security_gloves_t1', 'arknights_endfield', 'MI Security Gloves T1', 'hands', 'MI Security', 5, 'assets/gear/mi_security_gloves_t1.png', 'Agility +65', 'Defense +42; Intellect +43; Ultimate DMG Bonus +43.1%', 'MI Security 3-piece set effect', 1064),
    ('mi_security_scope_t1', 'arknights_endfield', 'MI Security Scope T1', 'kit', 'MI Security', 5, 'assets/gear/mi_security_scope_t1.png', 'Agility +32', 'Defense +21; Intellect +21; Crit Rate +10.4%', 'MI Security 3-piece set effect', 1065),
    ('pulser_labs_disruptor_suit', 'arknights_endfield', 'Pulser Labs Disruptor Suit', 'body', 'Pulser Labs', 5, 'assets/gear/pulser_labs_disruptor_suit.png', 'Intellect +87', 'Defense +56; Will +58; Arts Intensity +20', 'Pulser Labs 3-piece set effect', 1066),
    ('pulser_labs_gloves', 'arknights_endfield', 'Pulser Labs Gloves', 'hands', 'Pulser Labs', 5, 'assets/gear/pulser_labs_gloves.png', 'Will +65', 'Defense +42; Intellect +43; Cryo and Electric DMG Dealt Bonus +19.2%', 'Pulser Labs 3-piece set effect', 1067),
    ('pulser_labs_probe', 'arknights_endfield', 'Pulser Labs Probe', 'kit', 'Pulser Labs', 5, 'assets/gear/pulser_labs_probe.png', 'Intellect +32', 'Defense +21; Agility +21; Arts Intensity +41', 'Pulser Labs 3-piece set effect', 1068),
    ('pulser_labs_calibrator', 'arknights_endfield', 'Pulser Labs Calibrator', 'kit', 'Pulser Labs', 5, 'assets/gear/pulser_labs_calibrator.png', 'Intellect +41', 'Defense +21; Arts Intensity +41', 'Pulser Labs 3-piece set effect', 1069),
    ('pulser_labs_invasion_core', 'arknights_endfield', 'Pulser Labs Invasion Core', 'kit', 'Pulser Labs', 5, 'assets/gear/pulser_labs_invasion_core.png', 'Will +41', 'Defense +21; Ultimate DMG Bonus +51.7%', 'Pulser Labs 3-piece set effect', 1070),
    ('qingbo_heavy_armor', 'arknights_endfield', 'Qingbo Heavy Armor', 'body', 'Qingbo', 5, 'assets/gear/qingbo_heavy_armor.png', 'Agility +87', 'Defense +56; Strength +58; Ultimate Gain Efficiency +12.3%', 'Qingbo 3-piece set effect', 1071),
    ('qingbo_light_armor', 'arknights_endfield', 'Qingbo Light Armor', 'body', 'Qingbo', 5, 'assets/gear/qingbo_light_armor.png', 'Intellect +87', 'Defense +56; Will +58; Arts Intensity +20', 'Qingbo 3-piece set effect', 1072),
    ('qingbo_gauntlets', 'arknights_endfield', 'Qingbo Gauntlets', 'hands', 'Qingbo', 5, 'assets/gear/qingbo_gauntlets.png', 'Agility +65', 'Defense +42; Strength +43; All Skill DMG Bonus +23%', 'Qingbo 3-piece set effect', 1073),
    ('qingbo_gloves', 'arknights_endfield', 'Qingbo Gloves', 'hands', 'Qingbo', 5, 'assets/gear/qingbo_gloves.png', 'Intellect +65', 'Defense +42; Will +43; Ultimate Gain Efficiency +20.5%', 'Qingbo 3-piece set effect', 1074),
    ('qingbo_positioning_kit', 'arknights_endfield', 'Qingbo Positioning Kit', 'kit', 'Qingbo', 5, 'assets/gear/qingbo_positioning_kit.png', 'Agility +32', 'Defense +21; Strength +21; Battle Skill DMG Bonus +41.4%', 'Qingbo 3-piece set effect', 1075),
    ('qingbo_bamboo_cutter', 'arknights_endfield', 'Qingbo Bamboo Cutter', 'kit', 'Qingbo', 5, 'assets/gear/qingbo_bamboo_cutter.png', 'Strength +32', 'Defense +21; Agility +21; Heat and Nature DMG Dealt Bonus +23%', 'Qingbo 3-piece set effect', 1076),
    ('qingbo_cask', 'arknights_endfield', 'Qingbo Cask', 'kit', 'Qingbo', 5, 'assets/gear/qingbo_cask.png', 'Intellect +32', 'Defense +21; Will +21; Arts Intensity +41', 'Qingbo 3-piece set effect', 1077),
    ('swordmancer_light_armor', 'arknights_endfield', 'Swordmancer Light Armor', 'body', 'Swordmancer', 5, 'assets/gear/swordmancer_light_armor.png', 'Strength +87', 'Defense +56; Will +58; Ultimate Gain Efficiency +12.3%', 'Swordmancer 3-piece set effect', 1078),
    ('swordmancer_heavy_armor', 'arknights_endfield', 'Swordmancer Heavy Armor', 'body', 'Swordmancer', 5, 'assets/gear/swordmancer_heavy_armor.png', 'Agility +87', 'Defense +56; Strength +58; Arts Intensity +20', 'Swordmancer 3-piece set effect', 1079),
    ('swordmancer_tac_gloves', 'arknights_endfield', 'Swordmancer TAC Gloves', 'hands', 'Swordmancer', 5, 'assets/gear/swordmancer_tac_gloves.png', 'Strength +65', 'Defense +42; Will +43; Physical DMG Bonus +19.2%', 'Swordmancer 3-piece set effect', 1080),
    ('swordmancer_tac_gauntlets', 'arknights_endfield', 'Swordmancer TAC Gauntlets', 'hands', 'Swordmancer', 5, 'assets/gear/swordmancer_tac_gauntlets.png', 'Agility +65', 'Defense +42; Strength +43; Ultimate DMG Bonus +43.1%', 'Swordmancer 3-piece set effect', 1081),
    ('swordmancer_nav_beacon', 'arknights_endfield', 'Swordmancer NAV Beacon', 'kit', 'Swordmancer', 5, 'assets/gear/swordmancer_nav_beacon.png', 'Strength +41', 'Defense +21; Arts Intensity +41', 'Swordmancer 3-piece set effect', 1082),
    ('swordmancer_micro_filter', 'arknights_endfield', 'Swordmancer Micro Filter', 'kit', 'Swordmancer', 5, 'assets/gear/swordmancer_micro_filter.png', 'Strength +32', 'Defense +21; Will +21; Physical DMG Bonus +23%', 'Swordmancer 3-piece set effect', 1083),
    ('swordmancer_flint', 'arknights_endfield', 'Swordmancer Flint', 'kit', 'Swordmancer', 5, 'assets/gear/swordmancer_flint.png', 'Agility +32', 'Defense +21; Strength +21; Physical DMG Bonus +23%', 'Swordmancer 3-piece set effect', 1084),
    ('swordmancer_heavy_armor_t1', 'arknights_endfield', 'Swordmancer Heavy Armor T1', 'body', 'Swordmancer', 5, 'assets/gear/swordmancer_heavy_armor_t1.png', 'Agility +87', 'Defense +56; Strength +58; Physical DMG Bonus +11.5%', 'Swordmancer 3-piece set effect', 1085),
    ('swordmancer_tac_gauntlets_t1', 'arknights_endfield', 'Swordmancer TAC Gauntlets T1', 'hands', 'Swordmancer', 5, 'assets/gear/swordmancer_tac_gauntlets_t1.png', 'Strength +65', 'Defense +42; Will +43; Arts Intensity +34', 'Swordmancer 3-piece set effect', 1086),
    ('swordmancer_dagger', 'arknights_endfield', 'Swordmancer Dagger', 'kit', 'Swordmancer', 5, 'assets/gear/swordmancer_dagger.png', 'Agility +32', 'Defense +21; Strength +21; Ultimate DMG Bonus +51.7%', 'Swordmancer 3-piece set effect', 1087),
    ('tide_fall_light_armor', 'arknights_endfield', 'Tide Fall Light Armor', 'body', 'Tide Surge', 5, 'assets/gear/tide_fall_light_armor.png', 'Intellect +87', 'Defense +56; Strength +58; Ultimate Gain Efficiency +12.3%', 'Tide Surge 3-piece set effect', 1088),
    ('tide_surge_gauntlets', 'arknights_endfield', 'Tide Surge Gauntlets', 'hands', 'Tide Surge', 5, 'assets/gear/tide_surge_gauntlets.png', 'Strength +65', 'Defense +42; Will +43; Cryo and Electric DMG Dealt Bonus +19.2%', 'Tide Surge 3-piece set effect', 1089),
    ('hanging_river_o2_tube', 'arknights_endfield', 'Hanging River O2 Tube', 'kit', 'Tide Surge', 5, 'assets/gear/hanging_river_o2_tube.png', 'Strength +32', 'Defense +21; Will +21; Cryo and Electric DMG Dealt Bonus +23%', 'Tide Surge 3-piece set effect', 1090),
    ('turbid_cutting_torch', 'arknights_endfield', 'Turbid Cutting Torch', 'kit', 'Tide Surge', 5, 'assets/gear/turbid_cutting_torch.png', 'Intellect +32', 'Defense +21; Strength +21; Basic Attack DMG Bonus +27.6%', 'Tide Surge 3-piece set effect', 1091),
    ('type_50_yinglung_heavy_armor', 'arknights_endfield', 'Type 50 Yinglung Heavy Armor', 'body', 'Type 50 Yinglung', 5, 'assets/gear/type_50_yinglung_heavy_armor.png', 'Strength +87', 'Defense +56; Will +58; Physical DMG Bonus +11.5%', 'Type 50 Yinglung 3-piece set effect', 1092),
    ('type_50_yinglung_heavy_armor_t1', 'arknights_endfield', 'Type 50 Yinglung Heavy Armor T1', 'body', 'Type 50 Yinglung', 5, 'assets/gear/type_50_yinglung_heavy_armor_t1.png', 'Agility +87', 'Defense +56; Strength +58; Ultimate Gain Efficiency +12.3%', 'Type 50 Yinglung 3-piece set effect', 1093),
    ('type_50_yinglung_heavy_armor_t2', 'arknights_endfield', 'Type 50 Yinglung Heavy Armor T2', 'body', 'Type 50 Yinglung', 5, 'assets/gear/type_50_yinglung_heavy_armor_t2.png', 'Agility +87', 'Defense +56; Intellect +58; Combo Skill DMG Bonus +20.7%', 'Type 50 Yinglung 3-piece set effect', 1094),
    ('type_50_yinglung_light_armor', 'arknights_endfield', 'Type 50 Yinglung Light Armor', 'body', 'Type 50 Yinglung', 5, 'assets/gear/type_50_yinglung_light_armor.png', 'Will +87', 'Defense +56; Strength +58; All Skill DMG Bonus +13.8%', 'Type 50 Yinglung 3-piece set effect', 1095),
    ('type_50_yinglung_gloves', 'arknights_endfield', 'Type 50 Yinglung Gloves', 'hands', 'Type 50 Yinglung', 5, 'assets/gear/type_50_yinglung_gloves.png', 'Agility +65', 'Defense +42; Intellect +43; Combo Skill DMG Bonus +34.5%', 'Type 50 Yinglung 3-piece set effect', 1096),
    ('type_50_yinglung_gloves_t1', 'arknights_endfield', 'Type 50 Yinglung Gloves T1', 'hands', 'Type 50 Yinglung', 5, 'assets/gear/type_50_yinglung_gloves_t1.png', 'Will +65', 'Defense +42; Agility +43; Combo Skill DMG Bonus +34.5%', 'Type 50 Yinglung 3-piece set effect', 1097),
    ('type_50_yinglung_radar', 'arknights_endfield', 'Type 50 Yinglung Radar', 'kit', 'Type 50 Yinglung', 5, 'assets/gear/type_50_yinglung_radar.png', 'Strength +32', 'Defense +21; Will +21; Physical DMG Bonus +23%', 'Type 50 Yinglung 3-piece set effect', 1098),
    ('type_50_yinglung_radar_t1', 'arknights_endfield', 'Type 50 Yinglung Radar T1', 'kit', 'Type 50 Yinglung', 5, 'assets/gear/type_50_yinglung_radar_t1.png', 'Agility +32', 'Defense +21; Strength +21; Ultimate DMG Bonus +51.7%', 'Type 50 Yinglung 3-piece set effect', 1099),
    ('type_50_yinglung_radar_t2', 'arknights_endfield', 'Type 50 Yinglung Radar T2', 'kit', 'Type 50 Yinglung', 5, 'assets/gear/type_50_yinglung_radar_t2.png', 'Agility +32', 'Defense +21; Intellect +21; Combo Skill DMG Bonus +41.4%', 'Type 50 Yinglung 3-piece set effect', 1100),
    ('type_50_yinglung_knife', 'arknights_endfield', 'Type 50 Yinglung Knife', 'kit', 'Type 50 Yinglung', 5, 'assets/gear/type_50_yinglung_knife.png', 'Will +32', 'Defense +21; Agility +21; Combo Skill DMG Bonus +41.4%', 'Type 50 Yinglung 3-piece set effect', 1101),
    ('type_50_yinglung_knife_t1', 'arknights_endfield', 'Type 50 Yinglung Knife T1', 'kit', 'Type 50 Yinglung', 5, 'assets/gear/type_50_yinglung_knife_t1.png', 'Intellect +32', 'Defense +21; Strength +21; All Skill DMG Bonus +27.6%', 'Type 50 Yinglung 3-piece set effect', 1102),
    ('xiranflow_light_armor', 'arknights_endfield', 'Xiranflow Light Armor', 'body', 'Xiranflow', 5, 'assets/gear/xiranflow_light_armor.png', 'Will +87', 'Defense +56; Intellect +58; Cryo and Electric DMG Dealt Bonus +11.5%', 'Xiranflow 3-piece set effect', 1103),
    ('xiranflow_gloves', 'arknights_endfield', 'Xiranflow Gloves', 'hands', 'Xiranflow', 5, 'assets/gear/xiranflow_gloves.png', 'Will +65', 'Defense +42; Intellect +43; Cryo and Electric DMG Dealt Bonus +19.2%', 'Xiranflow 3-piece set effect', 1104),
    ('xiranflow_baton', 'arknights_endfield', 'Xiranflow Baton', 'kit', 'Xiranflow', 5, 'assets/gear/xiranflow_baton.png', 'Will +32', 'Defense +21; Intellect +21; Battle Skill DMG Bonus +41.4%', 'Xiranflow 3-piece set effect', 1105),
    ('aethertech_plating', 'arknights_endfield', 'Æthertech Plating', 'body', 'Æthertech', 5, 'assets/gear/aethertech_plating.png', 'Strength +87', 'Defense +56; Will +58; DMG Bonus vs. Staggered +20.7%', 'Æthertech 3-piece set effect', 1106),
    ('aethertech_gloves', 'arknights_endfield', 'Æthertech Gloves', 'hands', 'Æthertech', 5, 'assets/gear/aethertech_gloves.png', 'Agility +65', 'Defense +42; Strength +43; Arts Intensity +34', 'Æthertech 3-piece set effect', 1107),
    ('aethertech_light_gloves', 'arknights_endfield', 'Æthertech Light Gloves', 'hands', 'Æthertech', 5, 'assets/gear/aethertech_light_gloves.png', 'Will +65', 'Defense +42; Agility +43; All Skill DMG Bonus +23%', 'Æthertech 3-piece set effect', 1108),
    ('aethertech_analysis_band', 'arknights_endfield', 'Æthertech Analysis Band', 'kit', 'Æthertech', 5, 'assets/gear/aethertech_analysis_band.png', 'Strength +32', 'Defense +21; Will +21; Physical DMG Bonus +23%', 'Æthertech 3-piece set effect', 1109),
    ('aethertech_stabilizer', 'arknights_endfield', 'Æthertech Stabilizer', 'kit', 'Æthertech', 5, 'assets/gear/aethertech_stabilizer.png', 'Agility +32', 'Defense +21; Strength +21; Arts Intensity +41', 'Æthertech 3-piece set effect', 1110),
    ('aethertech_stabilizer_t1', 'arknights_endfield', 'Æthertech Stabilizer T1', 'kit', 'Æthertech', 5, 'assets/gear/aethertech_stabilizer_t1.png', 'Agility +32', 'Defense +21; Strength +21; Physical DMG Bonus +23%', 'Æthertech 3-piece set effect', 1111),
    ('aethertech_watch', 'arknights_endfield', 'Æthertech Watch', 'kit', 'Æthertech', 5, 'assets/gear/aethertech_watch.png', 'Strength +32', 'Defense +21; Agility +21; Battle Skill DMG Bonus +41.4%', 'Æthertech 3-piece set effect', 1112),
    ('aburrey_heavy_armor', 'arknights_endfield', 'Aburrey Heavy Armor', 'body', 'Aburrey''s Legacy', 4, 'assets/gear/aburrey_heavy_armor.png', 'Strength +61', 'Defense +40; Agility +41; All Skill DMG Bonus +9.8%', 'Aburrey''s Legacy 3-piece set effect', 1113),
    ('aburrey_heavy_armor_t1', 'arknights_endfield', 'Aburrey Heavy Armor T1', 'body', 'Aburrey''s Legacy', 4, 'assets/gear/aburrey_heavy_armor_t1.png', 'Agility +61', 'Defense +40; Strength +41; Combo Skill DMG Bonus +14.7%', 'Aburrey''s Legacy 3-piece set effect', 1114),
    ('aburrey_light_armor', 'arknights_endfield', 'Aburrey Light Armor', 'body', 'Aburrey''s Legacy', 4, 'assets/gear/aburrey_light_armor.png', 'Intellect +61', 'Defense +40; Strength +41; Ultimate Gain Efficiency +8.8%', 'Aburrey''s Legacy 3-piece set effect', 1115),
    ('aburrey_light_armor_t1', 'arknights_endfield', 'Aburrey Light Armor T1', 'body', 'Aburrey''s Legacy', 4, 'assets/gear/aburrey_light_armor_t1.png', 'Will +61', 'Defense +40; Agility +41; Battle Skill DMG Bonus +14.7%', 'Aburrey''s Legacy 3-piece set effect', 1116),
    ('aburrey_gauntlets', 'arknights_endfield', 'Aburrey Gauntlets', 'hands', 'Aburrey''s Legacy', 4, 'assets/gear/aburrey_gauntlets.png', 'Strength +46', 'Defense +30; Will +30; DMG Bonus vs. Staggered +24.5%', 'Aburrey''s Legacy 3-piece set effect', 1117),
    ('aburrey_uv_lamp', 'arknights_endfield', 'Aburrey UV Lamp', 'kit', 'Aburrey''s Legacy', 4, 'assets/gear/aburrey_uv_lamp.png', 'Strength +23', 'Defense +15; Agility +15; All Skill DMG Bonus +19.6%', 'Aburrey''s Legacy 3-piece set effect', 1118),
    ('aburrey_auditory_chip', 'arknights_endfield', 'Aburrey Auditory Chip', 'kit', 'Aburrey''s Legacy', 4, 'assets/gear/aburrey_auditory_chip.png', 'Strength +23', 'Defense +15; Will +15; DMG Bonus vs. Staggered +29.4%', 'Aburrey''s Legacy 3-piece set effect', 1119),
    ('aburrey_auditory_chip_t1', 'arknights_endfield', 'Aburrey Auditory Chip T1', 'kit', 'Aburrey''s Legacy', 4, 'assets/gear/aburrey_auditory_chip_t1.png', 'Agility +23', 'Defense +15; Strength +15; Combo Skill DMG Bonus +29.4%', 'Aburrey''s Legacy 3-piece set effect', 1120),
    ('aburrey_flashlight', 'arknights_endfield', 'Aburrey Flashlight', 'kit', 'Aburrey''s Legacy', 4, 'assets/gear/aburrey_flashlight.png', 'Intellect +23', 'Defense +15; Strength +15; Ultimate Gain Efficiency +17.5%', 'Aburrey''s Legacy 3-piece set effect', 1121),
    ('aburrey_sensor_chip', 'arknights_endfield', 'Aburrey Sensor Chip', 'kit', 'Aburrey''s Legacy', 4, 'assets/gear/aburrey_sensor_chip.png', 'Will +23', 'Defense +15; Agility +15; Battle Skill DMG Bonus +29.4%', 'Aburrey''s Legacy 3-piece set effect', 1122),
    ('aburrey_sensor_chip_t1', 'arknights_endfield', 'Aburrey Sensor Chip T1', 'kit', 'Aburrey''s Legacy', 4, 'assets/gear/aburrey_sensor_chip_t1.png', 'Will +23', 'Defense +15; Intellect +15; Battle Skill DMG Bonus +29.4%', 'Aburrey''s Legacy 3-piece set effect', 1123),
    ('armored_msgr_jacket', 'arknights_endfield', 'Armored MSGR Jacket', 'body', 'Armored MSGR', 4, 'assets/gear/armored_msgr_jacket.png', 'Strength +44', 'Defense +28; Agility +29; HP +10.5%', 'Armored MSGR 3-piece set effect', 1124),
    ('armored_msgr_gloves', 'arknights_endfield', 'Armored MSGR Gloves', 'hands', 'Armored MSGR', 4, 'assets/gear/armored_msgr_gloves.png', 'Strength +33', 'Defense +21; Will +22; Final DMG Reduction +8%', 'Armored MSGR 3-piece set effect', 1125),
    ('armored_msgr_gyro', 'arknights_endfield', 'Armored MSGR Gyro', 'kit', 'Armored MSGR', 4, 'assets/gear/armored_msgr_gyro.png', 'Strength +21', 'Defense +10; Attack +10.5%', 'Armored MSGR 3-piece set effect', 1126),
    ('armored_msgr_flashlight', 'arknights_endfield', 'Armored MSGR Flashlight', 'kit', 'Armored MSGR', 4, 'assets/gear/armored_msgr_flashlight.png', 'Strength +21', 'Defense +10; HP +21%', 'Armored MSGR 3-piece set effect', 1127),
    ('armored_msgr_jacket_t1', 'arknights_endfield', 'Armored MSGR Jacket T1', 'body', 'Armored MSGR', 4, 'assets/gear/armored_msgr_jacket_t1.png', 'Strength +61', 'Defense +40; Will +41; HP +14.7%', 'Armored MSGR 3-piece set effect', 1128),
    ('armored_msgr_gloves_t1', 'arknights_endfield', 'Armored MSGR Gloves T1', 'hands', 'Armored MSGR', 4, 'assets/gear/armored_msgr_gloves_t1.png', 'Strength +46', 'Defense +30; Agility +30; Attack +12.3%', 'Armored MSGR 3-piece set effect', 1129),
    ('armored_msgr_gloves_t2', 'arknights_endfield', 'Armored MSGR Gloves T2', 'hands', 'Armored MSGR', 4, 'assets/gear/armored_msgr_gloves_t2.png', 'Strength +46', 'Defense +30; Agility +30; Combo Skill DMG Bonus +24.5%', 'Armored MSGR 3-piece set effect', 1130),
    ('armored_msgr_gyro_t1', 'arknights_endfield', 'Armored MSGR Gyro T1', 'kit', 'Armored MSGR', 4, 'assets/gear/armored_msgr_gyro_t1.png', 'Strength +23', 'Defense +15; Will +15; Attack +14.7%', 'Armored MSGR 3-piece set effect', 1131),
    ('armored_msgr_flashlight_t1', 'arknights_endfield', 'Armored MSGR Flashlight T1', 'kit', 'Armored MSGR', 4, 'assets/gear/armored_msgr_flashlight_t1.png', 'Strength +23', 'Defense +15; Agility +15; Crit Rate +7.4%', 'Armored MSGR 3-piece set effect', 1132),
    ('catastrophe_heavy_armor', 'arknights_endfield', 'Catastrophe Heavy Armor', 'body', 'Catastrophe', 4, 'assets/gear/catastrophe_heavy_armor.png', 'Strength +61', 'Defense +40; Intellect +41; Ultimate DMG Bonus +18.4%', 'Catastrophe 3-piece set effect', 1133),
    ('catastrophe_heavy_armor_t1', 'arknights_endfield', 'Catastrophe Heavy Armor T1', 'body', 'Catastrophe', 4, 'assets/gear/catastrophe_heavy_armor_t1.png', 'Strength +61', 'Defense +40; Will +41; Ultimate Gain Efficiency +8.8%', 'Catastrophe 3-piece set effect', 1134),
    ('catastrophe_gloves', 'arknights_endfield', 'Catastrophe Gloves', 'hands', 'Catastrophe', 4, 'assets/gear/catastrophe_gloves.png', 'Will +46', 'Defense +30; Intellect +30; Arts Intensity +24', 'Catastrophe 3-piece set effect', 1135),
    ('catastrophe_gauze_cartridge', 'arknights_endfield', 'Catastrophe Gauze Cartridge', 'kit', 'Catastrophe', 4, 'assets/gear/catastrophe_gauze_cartridge.png', 'Strength +23', 'Defense +15; Intellect +15; Ultimate DMG Bonus +36.8%', 'Catastrophe 3-piece set effect', 1136),
    ('catastrophe_gauze_cartridge_t1', 'arknights_endfield', 'Catastrophe Gauze Cartridge T1', 'kit', 'Catastrophe', 4, 'assets/gear/catastrophe_gauze_cartridge_t1.png', 'Strength +23', 'Defense +15; Will +15; Secondary Attribute +14.7%', 'Catastrophe 3-piece set effect', 1137),
    ('catastrophe_filter', 'arknights_endfield', 'Catastrophe Filter', 'kit', 'Catastrophe', 4, 'assets/gear/catastrophe_filter.png', 'Will +23', 'Defense +15; Intellect +15; Arts Intensity +29', 'Catastrophe 3-piece set effect', 1138),
    ('mordvolt_insulation_vest', 'arknights_endfield', 'Mordvolt Insulation Vest', 'body', 'Mordvolt Insulation', 4, 'assets/gear/mordvolt_insulation_vest.png', 'Intellect +44', 'Defense +28; Strength +29; Attack +16.2%', 'Mordvolt Insulation 3-piece set effect', 1139),
    ('mordvolt_insulation_gloves', 'arknights_endfield', 'Mordvolt Insulation Gloves', 'hands', 'Mordvolt Insulation', 4, 'assets/gear/mordvolt_insulation_gloves.png', 'Intellect +33', 'Defense +21; Will +22; Arts DMG +9.2%', 'Mordvolt Insulation 3-piece set effect', 1140),
    ('mordvolt_insulation_wrench', 'arknights_endfield', 'Mordvolt Insulation Wrench', 'kit', 'Mordvolt Insulation', 4, 'assets/gear/mordvolt_insulation_wrench.png', 'Intellect +21', 'Defense +10; Attack +10.5%', 'Mordvolt Insulation 3-piece set effect', 1141),
    ('mordvolt_insulation_wrench_t1', 'arknights_endfield', 'Mordvolt Insulation Wrench T1', 'kit', 'Mordvolt Insulation', 4, 'assets/gear/mordvolt_insulation_wrench_t1.png', 'Intellect +21', 'Defense +10; Cryo and Electric DMG Dealt Bonus +11.7%', 'Mordvolt Insulation 3-piece set effect', 1142),
    ('mordvolt_insulation_battery', 'arknights_endfield', 'Mordvolt Insulation Battery', 'kit', 'Mordvolt Insulation', 4, 'assets/gear/mordvolt_insulation_battery.png', 'Intellect +21', 'Defense +10; Crit Rate +5.3%', 'Mordvolt Insulation 3-piece set effect', 1143),
    ('mordvolt_insulation_vest_t1', 'arknights_endfield', 'Mordvolt Insulation Vest T1', 'body', 'Mordvolt Insulation', 4, 'assets/gear/mordvolt_insulation_vest_t1.png', 'Intellect +61', 'Defense +40; Agility +41; Basic Attack DMG Bonus +9.8%', 'Mordvolt Insulation 3-piece set effect', 1144),
    ('mordvolt_insulation_vest_t2', 'arknights_endfield', 'Mordvolt Insulation Vest T2', 'body', 'Mordvolt Insulation', 4, 'assets/gear/mordvolt_insulation_vest_t2.png', 'Intellect +61', 'Defense +40; Will +41; HP +14.7%', 'Mordvolt Insulation 3-piece set effect', 1145),
    ('mordvolt_insulation_gloves_t1', 'arknights_endfield', 'Mordvolt Insulation Gloves T1', 'hands', 'Mordvolt Insulation', 4, 'assets/gear/mordvolt_insulation_gloves_t1.png', 'Intellect +46', 'Defense +30; Strength +30; Attack +12.3%', 'Mordvolt Insulation 3-piece set effect', 1146),
    ('mordvolt_insulation_wrench_t2', 'arknights_endfield', 'Mordvolt Insulation Wrench T2', 'kit', 'Mordvolt Insulation', 4, 'assets/gear/mordvolt_insulation_wrench_t2.png', 'Intellect +23', 'Defense +15; Agility +15; Attack +14.7%', 'Mordvolt Insulation 3-piece set effect', 1147),
    ('mordvolt_insulation_battery_t1', 'arknights_endfield', 'Mordvolt Insulation Battery T1', 'kit', 'Mordvolt Insulation', 4, 'assets/gear/mordvolt_insulation_battery_t1.png', 'Intellect +29', 'Defense +15; Ultimate Gain Efficiency +17.5%', 'Mordvolt Insulation 3-piece set effect', 1148),
    ('mordvolt_resistant_vest', 'arknights_endfield', 'Mordvolt Resistant Vest', 'body', 'Mordvolt Resistant', 4, 'assets/gear/mordvolt_resistant_vest.png', 'Will +44', 'Defense +28; Agility +29; HP +10.5%', 'Mordvolt Resistant 3-piece set effect', 1149),
    ('mordvolt_resistant_gloves', 'arknights_endfield', 'Mordvolt Resistant Gloves', 'hands', 'Mordvolt Resistant', 4, 'assets/gear/mordvolt_resistant_gloves.png', 'Will +33', 'Defense +21; Intellect +22; Treatment Bonus +8.8%', 'Mordvolt Resistant 3-piece set effect', 1150),
    ('mordvolt_resistant_wrench', 'arknights_endfield', 'Mordvolt Resistant Wrench', 'kit', 'Mordvolt Resistant', 4, 'assets/gear/mordvolt_resistant_wrench.png', 'Will +21', 'Defense +10; Attack +10.5%', 'Mordvolt Resistant 3-piece set effect', 1151),
    ('mordvolt_resistant_battery', 'arknights_endfield', 'Mordvolt Resistant Battery', 'kit', 'Mordvolt Resistant', 4, 'assets/gear/mordvolt_resistant_battery.png', 'Will +21', 'Defense +10; Treatment Bonus +10.5%', 'Mordvolt Resistant 3-piece set effect', 1152),
    ('mordvolt_resistant_vest_t1', 'arknights_endfield', 'Mordvolt Resistant Vest T1', 'body', 'Mordvolt Resistant', 4, 'assets/gear/mordvolt_resistant_vest_t1.png', 'Will +61', 'Defense +40; Intellect +41; HP +14.7%', 'Mordvolt Resistant 3-piece set effect', 1153),
    ('mordvolt_resistant_gloves_t1', 'arknights_endfield', 'Mordvolt Resistant Gloves T1', 'hands', 'Mordvolt Resistant', 4, 'assets/gear/mordvolt_resistant_gloves_t1.png', 'Will +46', 'Defense +30; Agility +30; Attack +12.3%', 'Mordvolt Resistant 3-piece set effect', 1154),
    ('mordvolt_resistant_battery_t1', 'arknights_endfield', 'Mordvolt Resistant Battery T1', 'kit', 'Mordvolt Resistant', 4, 'assets/gear/mordvolt_resistant_battery_t1.png', 'Will +23', 'Defense +15; Agility +15; Treatment Bonus +14.7%', 'Mordvolt Resistant 3-piece set effect', 1155),
    ('mordvolt_resistant_wrench_t1', 'arknights_endfield', 'Mordvolt Resistant Wrench T1', 'kit', 'Mordvolt Resistant', 4, 'assets/gear/mordvolt_resistant_wrench_t1.png', 'Will +23', 'Defense +15; Intellect +15; Attack +14.7%', 'Mordvolt Resistant 3-piece set effect', 1156),
    ('roving_msgr_jacket', 'arknights_endfield', 'Roving MSGR Jacket', 'body', 'Roving MSGR', 4, 'assets/gear/roving_msgr_jacket.png', 'Agility +44', 'Defense +28; Intellect +29; Attack +16.2%', 'Roving MSGR 3-piece set effect', 1157),
    ('roving_msgr_fists', 'arknights_endfield', 'Roving MSGR Fists', 'hands', 'Roving MSGR', 4, 'assets/gear/roving_msgr_fists.png', 'Agility +33', 'Defense +21; Strength +22; Physical DMG Bonus +9.7%', 'Roving MSGR 3-piece set effect', 1158),
    ('roving_msgr_gyro', 'arknights_endfield', 'Roving MSGR Gyro', 'kit', 'Roving MSGR', 4, 'assets/gear/roving_msgr_gyro.png', 'Agility +21', 'Defense +10; Attack +10.5%', 'Roving MSGR 3-piece set effect', 1159),
    ('roving_msgr_flashlight', 'arknights_endfield', 'Roving MSGR Flashlight', 'kit', 'Roving MSGR', 4, 'assets/gear/roving_msgr_flashlight.png', 'Agility +21', 'Defense +10; Combo Skill DMG Bonus +21%', 'Roving MSGR 3-piece set effect', 1160),
    ('roving_msgr_jacket_t1', 'arknights_endfield', 'Roving MSGR Jacket T1', 'body', 'Roving MSGR', 4, 'assets/gear/roving_msgr_jacket_t1.png', 'Agility +61', 'Defense +40; Intellect +41; HP +14.7%', 'Roving MSGR 3-piece set effect', 1161),
    ('roving_msgr_fists_t1', 'arknights_endfield', 'Roving MSGR Fists T1', 'hands', 'Roving MSGR', 4, 'assets/gear/roving_msgr_fists_t1.png', 'Agility +46', 'Defense +30; Strength +30; Attack +12.3%', 'Roving MSGR 3-piece set effect', 1162),
    ('roving_msgr_flashlight_t1', 'arknights_endfield', 'Roving MSGR Flashlight T1', 'kit', 'Roving MSGR', 4, 'assets/gear/roving_msgr_flashlight_t1.png', 'Agility +23', 'Defense +15; Strength +15; Combo Skill DMG Bonus +29.4%', 'Roving MSGR 3-piece set effect', 1163),
    ('roving_msgr_flashlight_t2', 'arknights_endfield', 'Roving MSGR Flashlight T2', 'kit', 'Roving MSGR', 4, 'assets/gear/roving_msgr_flashlight_t2.png', 'Agility +23', 'Defense +15; Strength +15; Ultimate DMG Bonus +36.8%', 'Roving MSGR 3-piece set effect', 1164),
    ('roving_msgr_gyro_t1', 'arknights_endfield', 'Roving MSGR Gyro T1', 'kit', 'Roving MSGR', 4, 'assets/gear/roving_msgr_gyro_t1.png', 'Agility +23', 'Defense +15; Intellect +15; Attack +14.7%', 'Roving MSGR 3-piece set effect', 1165),
    ('aic_heavy_armor', 'arknights_endfield', 'AIC Heavy Armor', 'body', 'AIC Heavy', 2, 'assets/gear/aic_heavy_armor.png', 'Strength +30', 'Defense +22; Agility +30; Final DMG Reduction +3.9%', 'AIC Heavy 3-piece set effect', 1166),
    ('aic_gauntlets', 'arknights_endfield', 'AIC Gauntlets', 'hands', 'AIC Heavy', 2, 'assets/gear/aic_gauntlets.png', 'Strength +23', 'Defense +16; Will +23; Final DMG Reduction +6.3%', 'AIC Heavy 3-piece set effect', 1167),
    ('aic_heavy_plate', 'arknights_endfield', 'AIC Heavy Plate', 'kit', 'AIC Heavy', 2, 'assets/gear/aic_heavy_plate.png', 'Strength +16', 'Defense +8; Final DMG Reduction +7.5%', 'AIC Heavy 3-piece set effect', 1168),
    ('aic_alloy_plate', 'arknights_endfield', 'AIC Alloy Plate', 'kit', 'AIC Heavy', 2, 'assets/gear/aic_alloy_plate.png', 'Agility +16', 'Defense +8; Final DMG Reduction +7.5%', 'AIC Heavy 3-piece set effect', 1169),
    ('aic_light_armor', 'arknights_endfield', 'AIC Light Armor', 'body', 'AIC Light', 2, 'assets/gear/aic_light_armor.png', 'Intellect +30', 'Defense +22; Will +30; Battle Skill DMG Bonus +8.1%', 'AIC Light 3-piece set effect', 1170),
    ('aic_tactical_gloves', 'arknights_endfield', 'AIC Tactical Gloves', 'hands', 'AIC Light', 2, 'assets/gear/aic_tactical_gloves.png', 'Intellect +23', 'Defense +16; Agility +23; Combo Skill DMG Bonus +13.5%', 'AIC Light 3-piece set effect', 1171),
    ('aic_light_plate', 'arknights_endfield', 'AIC Light Plate', 'kit', 'AIC Light', 2, 'assets/gear/aic_light_plate.png', 'Intellect +16', 'Defense +8; Combo Skill DMG Bonus +16.2%', 'AIC Light 3-piece set effect', 1172),
    ('aic_ceramic_plate', 'arknights_endfield', 'AIC Ceramic Plate', 'kit', 'AIC Light', 2, 'assets/gear/aic_ceramic_plate.png', 'Will +16', 'Defense +8; Battle Skill DMG Bonus +16.2%', 'AIC Light 3-piece set effect', 1173),
    ('redeemer_armor', 'arknights_endfield', 'Redeemer Armor', 'body', null, 5, 'assets/gear/redeemer_armor.png', null, null, null, 9000),
    ('redeemer_gloves', 'arknights_endfield', 'Redeemer Gloves', 'hands', null, 5, 'assets/gear/redeemer_gloves.png', null, null, null, 9001),
    ('redeemer_hands', 'arknights_endfield', 'Redeemer Hands', 'hands', null, 5, 'assets/gear/redeemer_hands.png', null, null, null, 9002),
    ('redeemer_plates', 'arknights_endfield', 'Redeemer Plates', 'body', null, 5, 'assets/gear/redeemer_plates.png', null, null, null, 9003),
    ('redeemer_seal', 'arknights_endfield', 'Redeemer Seal', 'kit', null, 5, 'assets/gear/redeemer_seal.png', null, null, null, 9004),
    ('redeemer_seal_t1', 'arknights_endfield', 'Redeemer Seal T1', 'kit', null, 5, 'assets/gear/redeemer_seal_t1.png', null, null, null, 9005),
    ('redeemer_tag', 'arknights_endfield', 'Redeemer Tag', 'kit', null, 5, 'assets/gear/redeemer_tag.png', null, null, null, 9006),
    ('redeemer_tag_t1', 'arknights_endfield', 'Redeemer Tag T1', 'kit', null, 5, 'assets/gear/redeemer_tag_t1.png', null, null, null, 9007),
    ('miner_armor_t1', 'arknights_endfield', 'Miner Armor T1', 'body', null, 4, 'assets/gear/miner_armor_t1.png', null, null, null, 9008),
    ('miner_comm_t1', 'arknights_endfield', 'Miner Comm T1', 'kit', null, 4, 'assets/gear/miner_comm_t1.png', null, null, null, 9009),
    ('miner_compression_core_t1', 'arknights_endfield', 'Miner Compression Core T1', 'kit', null, 4, 'assets/gear/miner_compression_core_t1.png', null, null, null, 9010),
    ('miner_drive_wheel_t1', 'arknights_endfield', 'Miner Drive Wheel T1', 'kit', null, 4, 'assets/gear/miner_drive_wheel_t1.png', null, null, null, 9011),
    ('miner_fists_t1', 'arknights_endfield', 'Miner Fists T1', 'hands', null, 4, 'assets/gear/miner_fists_t1.png', null, null, null, 9012),
    ('miner_gloves_t2', 'arknights_endfield', 'Miner Gloves T2', 'hands', null, 4, 'assets/gear/miner_gloves_t2.png', null, null, null, 9013),
    ('miner_overalls_t1', 'arknights_endfield', 'Miner Overalls T1', 'body', null, 4, 'assets/gear/miner_overalls_t1.png', null, null, null, 9014),
    ('miner_turbine_t1', 'arknights_endfield', 'Miner Turbine T1', 'kit', null, 4, 'assets/gear/miner_turbine_t1.png', null, null, null, 9015),
    ('miner_comm', 'arknights_endfield', 'Miner Comm', 'kit', null, 3, 'assets/gear/miner_comm.png', null, null, null, 9016),
    ('miner_compression_core', 'arknights_endfield', 'Miner Compression Core', 'kit', null, 3, 'assets/gear/miner_compression_core.png', null, null, null, 9017),
    ('miner_drive_wheel', 'arknights_endfield', 'Miner Drive Wheel', 'kit', null, 3, 'assets/gear/miner_drive_wheel.png', null, null, null, 9018),
    ('miner_gauntlets_t1', 'arknights_endfield', 'Miner Gauntlets T1', 'hands', null, 3, 'assets/gear/miner_gauntlets_t1.png', null, null, null, 9019),
    ('miner_gloves_t1', 'arknights_endfield', 'Miner Gloves T1', 'hands', null, 3, 'assets/gear/miner_gloves_t1.png', null, null, null, 9020),
    ('miner_turbine', 'arknights_endfield', 'Miner Turbine', 'kit', null, 3, 'assets/gear/miner_turbine.png', null, null, null, 9021),
    ('emergency_comm', 'arknights_endfield', 'Emergency Comm', 'kit', null, 2, 'assets/gear/emergency_comm.png', null, null, null, 9022),
    ('emergency_compression_core', 'arknights_endfield', 'Emergency Compression Core', 'kit', null, 2, 'assets/gear/emergency_compression_core.png', null, null, null, 9023),
    ('miner_armor', 'arknights_endfield', 'Miner Armor', 'body', null, 2, 'assets/gear/miner_armor.png', null, null, null, 9024),
    ('miner_cleansuit', 'arknights_endfield', 'Miner Cleansuit', 'body', null, 2, 'assets/gear/miner_cleansuit.png', null, null, null, 9025),
    ('miner_fists', 'arknights_endfield', 'Miner Fists', 'hands', null, 2, 'assets/gear/miner_fists.png', null, null, null, 9026),
    ('miner_gauntlets', 'arknights_endfield', 'Miner Gauntlets', 'hands', null, 2, 'assets/gear/miner_gauntlets.png', null, null, null, 9027),
    ('miner_gloves', 'arknights_endfield', 'Miner Gloves', 'hands', null, 2, 'assets/gear/miner_gloves.png', null, null, null, 9028),
    ('miner_overalls', 'arknights_endfield', 'Miner Overalls', 'body', null, 2, 'assets/gear/miner_overalls.png', null, null, null, 9029),
    ('miner_vest', 'arknights_endfield', 'Miner Vest', 'body', null, 2, 'assets/gear/miner_vest.png', null, null, null, 9030),
    ('miner_wrists', 'arknights_endfield', 'Miner Wrists', 'hands', null, 2, 'assets/gear/miner_wrists.png', null, null, null, 9031),
    ('prototype_heavy_armor', 'arknights_endfield', 'Prototype Heavy Armor', 'body', null, 2, 'assets/gear/prototype_heavy_armor.png', null, null, null, 9032),
    ('prototype_heavy_armor_t1', 'arknights_endfield', 'Prototype Heavy Armor T1', 'body', null, 2, 'assets/gear/prototype_heavy_armor_t1.png', null, null, null, 9033),
    ('basic_armor', 'arknights_endfield', 'Basic Armor', 'body', null, 1, 'assets/gear/basic_armor.png', null, null, null, 9034),
    ('basic_gauntlets', 'arknights_endfield', 'Basic Gauntlets', 'hands', null, 1, 'assets/gear/basic_gauntlets.png', null, null, null, 9035),
    ('basic_gloves', 'arknights_endfield', 'Basic Gloves', 'hands', null, 1, 'assets/gear/basic_gloves.png', null, null, null, 9036),
    ('basic_ppe', 'arknights_endfield', 'Basic PPE', 'body', null, 1, 'assets/gear/basic_ppe.png', null, null, null, 9037)
on conflict (gear_key) do update set
    game = excluded.game,
    name = excluded.name,
    gear_slot = excluded.gear_slot,
    set_name = excluded.set_name,
    rarity = excluded.rarity,
    icon_path = excluded.icon_path,
    main_attribute = excluded.main_attribute,
    secondary_attribute = excluded.secondary_attribute,
    passive_name = excluded.passive_name,
    sort_order = excluded.sort_order,
    updated_at = now();

commit;
