-- Complete Arknights: Endfield gear catalog.
-- Generated from Endfield Talos Wiki on 2026-08-01.
-- Run this file in the Supabase SQL Editor.

begin;

insert into public.gear_sets (set_key, name, description)
values
    ('aburrey_legacy', 'Aburrey''s Legacy', '3-piece set effect: Wearer''s Skill DMG +24%. When the wearer casts a battle skill, combo skill, or ultimate, the wearer gains ATK +5% for 15s. The buff from each of the three skill types is unique and does not stack with itself.'),
    ('aethertech', 'Æthertech', '3-piece set effect: Wearer''s ATK +8%. After the wearer applies , the wearer gains Physical DMG +8% for 15s. This effect can reach 4 stacks. If the target already has 4 stack(s) of , the wearer gains an additional Physical DMG +16% for 10s. This effect cannot stack.'),
    ('aic_fieldwork', 'AIC Fieldwork', '3-piece set effect: Wearer gains DMG Dealt +20% for all types of DMG, 10% DMG Reduction against all types of DMG, and Ultimate Gain Efficiency +10%.'),
    ('aic_heavy', 'AIC Heavy', '3-piece set effect: Wearer''s HP +500. After the wearer defeats an enemy, the wearer restores 100 HP. Effect trigger cooldown: 5s.'),
    ('aic_light', 'AIC Light', '3-piece set effect: Wearer''s HP +500. After the wearer defeats an enemy, the wearer gains ATK +20 for 5s.'),
    ('armored_msgr', 'Armored MSGR', '3-piece set effect: Wearer''s Strength +50. When the wearer''s HP is below 50%, the wearer gains 30% DMG Reduction against all types of DMG.'),
    ('bonekrusha', 'Bonekrusha', '3-piece set effect: Wearer''s ATK +15%. When the wearer casts a combo skill, the wearer gains 1 stack of Bonekrushing Smash that grants the wearer''s next battle skill DMG Dealt +30%. Bonekrushing Smash can stack 2 time(s).'),
    ('catastrophe', 'Catastrophe', '3-piece set effect: Wearer''s Ultimate Gain Efficiency +20%. The wearer casts a battle skill, the action 50 SP. This effect only triggers 1 time per battle.'),
    ('eternal_xiranite', 'Eternal Xiranite', '3-piece set effect: Wearer''s HP +1000. After the wearer applies , , , or , other teammates gain DMG Dealt +16% for 15s. This effect cannot stack.'),
    ('frontiers', 'Frontiers', '3-piece set effect: Wearer''s Combo Skill Cooldown Reduction +15%. After the wearer''s skill recovers SP, the team gains DMG +16% for 15s. This effect cannot stack.'),
    ('grizzled_edge', 'Grizzled Edge', '3-piece set effect: Wearer''s ATK +8%. When the wearer applies or , the wearer gains Physical DMG Dealt +[6% × Max number of {{G stacks from one enemy]}} for 20s. If the target already has , is Staggered, or has attached , increase the aforementioned buff to 1.5 times. This buff cannot stack.'),
    ('hot_work', 'Hot Work', '3-piece set effect: Wearer''s Arts Intensity +30. After the wearer applies , the wearer gains Heat DMG +50% for 10s. After the wearer applies , the wearer gains Nature DMG +50% for 10s. The aforementioned effects cannot stack.'),
    ('lynx', 'LYNX', '3-piece set effect: Wearer''s HP Treatment Efficiency +20%. After the wearer gives HP treatment to an allied target, that target also gains 15% DMG Reduction against all types of DMG for 10s. If the said treatment exceeds the target''s Max HP, the target gains 30% DMG Reduction against all types of DMG. The aforementioned effects cannot stack.'),
    ('mi_security', 'MI Security', '3-piece set effect: Wearer''s Critical Rate +5%. After the wearer scores a critical hit, the wearer gains ATK +5% for 5s. This effect can reach 5 stacks. At max stacks, grant an additional Critical Rate +5%. This effect cannot stack.'),
    ('mordvolt_insulation', 'Mordvolt Insulation', '3-piece set effect: Wearer''s Intellect +50. When the wearer''s HP is above 80%, Arts DMG +20%.'),
    ('mordvolt_resistant', 'Mordvolt Resistant', '3-piece set effect: Wearer''s Will +50. When the wearer''s HP is below 50%, Treatment Effect +30%.'),
    ('pulser_labs', 'Pulser Labs', '3-piece set effect: Wearer''s Arts Intensity +30. After the wearer applies , the wearer gains Electric DMG +50% for 10s. After the wearer applies , the wearer gains Cryo DMG +50% for 10s. The aforementioned effects cannot stack.'),
    ('qingbo', 'Qingbo', '3-piece set effect: Wearer''s Combo Skill Cooldown Reduction +15%. When the wearer casts a combo skill, the wearer gains Skill DMG Dealt +20% (for every skill) for 15s. This effect can reach 2 stacks. Duration of each stack is counted separately.'),
    ('roving_msgr', 'Roving MSGR', '3-piece set effect: Wearer''s Agility +50. When the wearer''s HP is above 80%, Physical DMG +20%.'),
    ('swordmancer', 'Swordmancer', '3-piece set effect: Wearer''s Stagger Efficiency Bonus +20%. After the wearer applies a , the wearer also performs 1 hit that deals 250% ATK of Physical DMG and [10 Stagger]. Effect trigger cooldown: 15s.'),
    ('tide_surge', 'Tide Surge', '3-piece set effect: Wearer''s Skill DMG Dealt +20%. After the wearer applies 2 or more stacks of on the enemy, the wearer gains Arts DMG Dealt +35% for 15s. This effect cannot stack.'),
    ('type_50_yinglung', 'Type 50 Yinglung', '3-piece set effect: Wearer''s ATK +15%. When any operator in the team casts a battle skill, the wearer gains 1 stack of Yinglung''s Edge that gives DMG +20% to the wearer''s next combo skill. Yinglung''s Edge can stack 3 time(s).'),
    ('xiranflow', 'Xiranflow', '3-piece set effect: Wearer''s ATK +10%. Whenever the wearer or , the wearer gains a number of buff stacks equal to the of the Arts Reaction consumed, with each buff stack giving Electric DMG Dealt and Nature DMG Dealt +15% for 25s. Max number of buff stacks: 3. Duration of each stack is counted separately.')
on conflict (set_key) do update set
    name = excluded.name,
    description = excluded.description,
    updated_at = now();

insert into public.gear_items
    (gear_key, category, name, set_key, rarity, main_stat, main_value,
     sec_stat, sec_value, sub_stat, sub_value, def_value, icon)
values
    ('aic_fieldwork_armor', 'armor', 'AIC Fieldwork Armor', 'aic_fieldwork', 5, 'Main Attribute', 74, 'Secondary Attribute', 49, 'Arts DMG Dealt Bonus %', 9.3, 48, 'assets/gear/aic_fieldwork_armor.png'),
    ('aic_fieldwork_plate', 'armor', 'AIC Fieldwork Plate', 'aic_fieldwork', 5, 'Main Attribute', 74, 'Secondary Attribute', 49, 'Ultimate Gain Efficiency %', 10.5, 48, 'assets/gear/aic_fieldwork_plate.png'),
    ('aic_fieldwork_vest', 'armor', 'AIC Fieldwork Vest', 'aic_fieldwork', 5, 'Secondary Attribute', 74, 'Main Attribute', 49, 'Secondary Attribute', 8.9, 48, 'assets/gear/aic_fieldwork_vest.png'),
    ('bonekrusha_heavy_armor', 'armor', 'Bonekrusha Heavy Armor', 'bonekrusha', 5, 'Agility', 87, 'Intellect', 58, 'Ultimate Gain Efficiency %', 12.3, 56, 'assets/gear/bonekrusha_heavy_armor.png'),
    ('bonekrusha_heavy_armor_t1', 'armor', 'Bonekrusha Heavy Armor T1', 'bonekrusha', 5, 'Agility', 87, 'Strength', 58, 'Combo Skill DMG Bonus %', 20.7, 56, 'assets/gear/bonekrusha_heavy_armor_t1.png'),
    ('bonekrusha_heavy_armor_t2', 'armor', 'Bonekrusha Heavy Armor T2', 'bonekrusha', 5, 'Agility', 87, 'Strength', 58, 'Cryo and Electric DMG Dealt Bonus %', 11.5, 56, 'assets/gear/bonekrusha_heavy_armor_t2.png'),
    ('bonekrusha_armor', 'armor', 'Bonekrusha Poncho', 'bonekrusha', 5, 'Will', 87, 'Strength', 58, 'Combo Skill DMG Bonus %', 20.7, 56, 'assets/gear/bonekrusha_armor.png'),
    ('bonekrusha_poncho_t1', 'armor', 'Bonekrusha Poncho T1', 'bonekrusha', 5, 'Will', 87, 'Agility', 58, 'Ultimate Gain Efficiency %', 12.3, 56, 'assets/gear/bonekrusha_poncho_t1.png'),
    ('eternal_xiranite_armor', 'armor', 'Eternal Xiranite Armor', 'eternal_xiranite', 5, 'Will', 87, 'Intellect', 58, 'Arts Intensity', 20.7, 56, 'assets/gear/eternal_xiranite_armor.png'),
    ('eternal_xiranite_light_armor', 'armor', 'Eternal Xiranite Light Armor', 'eternal_xiranite', 5, 'Will', 110, null, null, 'Ultimate Gain Efficiency %', 12.3, 56, 'assets/gear/eternal_xiranite_light_armor.png'),
    ('eternal_xiranite_light_armor_t1', 'armor', 'Eternal Xiranite Light Armor T1', 'eternal_xiranite', 5, 'Intellect', 87, 'Will', 58, 'Secondary Attribute', 10.4, 56, 'assets/gear/eternal_xiranite_light_armor_t1.png'),
    ('frontiers_armor', 'armor', 'Frontiers Armor', 'frontiers', 5, 'Strength', 87, 'Intellect', 58, 'Ultimate DMG Bonus %', 25.9, 56, 'assets/gear/frontiers_armor.png'),
    ('frontiers_armor_t1', 'armor', 'Frontiers Armor T1', 'frontiers', 5, 'Strength', 87, 'Agility', 58, 'Battle Skill DMG Bonus %', 20.7, 56, 'assets/gear/frontiers_armor_t1.png'),
    ('frontiers_armor_t2', 'armor', 'Frontiers Armor T2', 'frontiers', 5, 'Agility', 87, 'Intellect', 58, 'Battle Skill DMG Bonus %', 20.7, 56, 'assets/gear/frontiers_armor_t2.png'),
    ('frontiers_armor_t3', 'armor', 'Frontiers Armor T3', 'frontiers', 5, 'Agility', 87, 'Intellect', 58, 'Secondary Attribute', 10.4, 56, 'assets/gear/frontiers_armor_t3.png'),
    ('frontiers_protection_suit', 'armor', 'Frontiers Protection Suit', 'frontiers', 5, 'Intellect', 87, 'Agility', 58, 'Ultimate Gain Efficiency %', 12.3, 56, 'assets/gear/frontiers_protection_suit.png'),
    ('grizzled_edge_armor', 'armor', 'Grizzled Edge Armor', 'grizzled_edge', 5, 'Strength', 87, 'Will', 58, 'Physical DMG Bonus %', 11.5, 56, 'assets/gear/grizzled_edge_armor.png'),
    ('grizzled_edge_armor_t1', 'armor', 'Grizzled Edge Armor T1', 'grizzled_edge', 5, 'Agility', 87, 'Strength', 58, 'Arts Intensity', 20.7, 56, 'assets/gear/grizzled_edge_armor_t1.png'),
    ('hot_work_exo_rig', 'armor', 'Hot Work Exo-Rig', 'hot_work', 5, 'Intellect', 87, 'Will', 58, 'Heat and Nature DMG Dealt Bonus %', 11.5, 56, 'assets/gear/hot_work_exo_rig.png'),
    ('hot_work_armor', 'armor', 'Hot Work Exoskeleton', 'hot_work', 5, 'Strength', 87, 'Agility', 58, 'Heat and Nature DMG Dealt Bonus %', 11.5, 56, 'assets/gear/hot_work_armor.png'),
    ('lynx_cuirass', 'armor', 'LYNX Cuirass', 'lynx', 5, 'Will', 87, 'Intellect', 58, 'Treatment Effect %', 10.3, 56, 'assets/gear/lynx_cuirass.png'),
    ('lynx_cuirass_t1', 'armor', 'LYNX Cuirass T1', 'lynx', 5, 'Will', 87, 'Agility', 58, 'Ultimate Gain Efficiency %', 12.3, 56, 'assets/gear/lynx_cuirass_t1.png'),
    ('lynx_armor', 'armor', 'LYNX Heavy Armor', 'lynx', 5, 'Strength', 87, 'Will', 58, 'Treatment Effect %', 10.3, 56, 'assets/gear/lynx_armor.png'),
    ('mi_security_armor', 'armor', 'MI Security Armor', 'mi_security', 5, 'Agility', 87, 'Strength', 58, 'Arts Intensity', 20.7, 56, 'assets/gear/mi_security_armor.png'),
    ('mi_security_armor_t1', 'armor', 'MI Security Armor T1', 'mi_security', 5, 'Agility', 87, 'Intellect', 58, 'Ultimate Gain Efficiency %', 12.3, 56, 'assets/gear/mi_security_armor_t1.png'),
    ('mi_security_overalls', 'armor', 'MI Security Overalls', 'mi_security', 5, 'Intellect', 87, 'Agility', 58, 'Basic Attack DMG Bonus %', 13.8, 56, 'assets/gear/mi_security_overalls.png'),
    ('mi_security_overalls_t1', 'armor', 'MI Security Overalls T1', 'mi_security', 5, 'Intellect', 87, 'Will', 58, 'Crit Rate %', 5.2, 56, 'assets/gear/mi_security_overalls_t1.png'),
    ('mi_security_overalls_t2', 'armor', 'MI Security Overalls T2', 'mi_security', 5, 'Will', 87, 'Agility', 58, 'Battle Skill DMG Bonus %', 20.7, 56, 'assets/gear/mi_security_overalls_t2.png'),
    ('pulser_labs_armor', 'armor', 'Pulser Labs Disruptor Suit', 'pulser_labs', 5, 'Intellect', 87, 'Will', 58, 'Arts Intensity', 20.7, 56, 'assets/gear/pulser_labs_armor.png'),
    ('qingbo_heavy_armor', 'armor', 'Qingbo Heavy Armor', 'qingbo', 5, 'Agility', 87, 'Strength', 58, 'Ultimate Gain Efficiency %', 12.3, 56, 'assets/gear/qingbo_heavy_armor.png'),
    ('qingbo_light_armor', 'armor', 'Qingbo Light Armor', 'qingbo', 5, 'Intellect', 87, 'Will', 58, 'Arts Intensity', 20.7, 56, 'assets/gear/qingbo_light_armor.png'),
    ('redeemer_armor', 'armor', 'Redeemer Armor', null, 5, 'Intellect', 115, null, null, 'Ultimate Gain Efficiency %', 12.9, 56, 'assets/gear/redeemer_armor.png'),
    ('redeemer_plates', 'armor', 'Redeemer Plates', null, 5, 'Agility', 115, null, null, 'Basic Attack DMG Bonus %', 14.4, 56, 'assets/gear/redeemer_plates.png'),
    ('rift_trekker_heavy_armor', 'armor', 'Rift Trekker Heavy Armor', null, 5, 'Strength', 115, null, null, 'Arts Intensity', 21.6, 56, 'assets/gear/rift_trekker_heavy_armor.png'),
    ('rift_trekker_light_armor', 'armor', 'Rift Trekker Light Armor', null, 5, 'Will', 115, null, null, 'Treatment Effect %', 10.8, 56, 'assets/gear/rift_trekker_light_armor.png'),
    ('swordmancer_fiber_armor', 'armor', 'Swordmancer Fiber Armor', 'swordmancer', 5, 'Strength', 87, 'Will', 58, 'Physical DMG Bonus %', 11.5, 56, 'assets/gear/swordmancer_fiber_armor.png'),
    ('swordmancer_armor', 'armor', 'Swordmancer Heavy Armor', 'swordmancer', 5, 'Agility', 87, 'Strength', 58, 'Arts Intensity', 20.7, 56, 'assets/gear/swordmancer_armor.png'),
    ('swordmancer_heavy_armor_t1', 'armor', 'Swordmancer Heavy Armor T1', 'swordmancer', 5, 'Agility', 87, 'Strength', 58, 'Physical DMG Bonus %', 11.5, 56, 'assets/gear/swordmancer_heavy_armor_t1.png'),
    ('swordmancer_light_armor', 'armor', 'Swordmancer Light Armor', 'swordmancer', 5, 'Strength', 87, 'Will', 58, 'Ultimate Gain Efficiency %', 12.3, 56, 'assets/gear/swordmancer_light_armor.png'),
    ('tide_surge_armor', 'armor', 'Tide Fall Light Armor', 'tide_surge', 5, 'Intellect', 87, 'Strength', 58, 'Ultimate Gain Efficiency %', 12.3, 56, 'assets/gear/tide_surge_armor.png'),
    ('type_50_yinglung_armor', 'armor', 'Type 50 Yinglung Heavy Armor', 'type_50_yinglung', 5, 'Strength', 87, 'Will', 58, 'Physical DMG Bonus %', 11.5, 56, 'assets/gear/type_50_yinglung_armor.png'),
    ('type_50_yinglung_heavy_armor_t1', 'armor', 'Type 50 Yinglung Heavy Armor T1', 'type_50_yinglung', 5, 'Agility', 87, 'Strength', 58, 'Ultimate Gain Efficiency %', 12.3, 56, 'assets/gear/type_50_yinglung_heavy_armor_t1.png'),
    ('type_50_yinglung_heavy_armor_t2', 'armor', 'Type 50 Yinglung Heavy Armor T2', 'type_50_yinglung', 5, 'Agility', 87, 'Intellect', 58, 'Combo Skill DMG Bonus %', 20.7, 56, 'assets/gear/type_50_yinglung_heavy_armor_t2.png'),
    ('type_50_yinglung_light_armor', 'armor', 'Type 50 Yinglung Light Armor', 'type_50_yinglung', 5, 'Will', 87, 'Strength', 58, 'Skill DMG Bonus %', 13.8, 56, 'assets/gear/type_50_yinglung_light_armor.png'),
    ('xiranflow_light_armor', 'armor', 'Xiranflow Light Armor', 'xiranflow', 5, 'Will', 87, 'Intellect', 58, 'Cryo and Electric DMG Dealt Bonus %', 11.5, 56, 'assets/gear/xiranflow_light_armor.png'),
    ('aethertech_armor', 'armor', 'Æthertech Plating', 'aethertech', 5, 'Strength', 87, 'Will', 58, 'DMG Bonus vs. Staggered', 20.7, 56, 'assets/gear/aethertech_armor.png'),
    ('aburrey_heavy_armor', 'armor', 'Aburrey Heavy Armor', 'aburrey_legacy', 4, 'Strength', 61, 'Agility', 41, 'Skill DMG Bonus %', 9.8, 40, 'assets/gear/aburrey_heavy_armor.png'),
    ('aburrey_heavy_armor_t1', 'armor', 'Aburrey Heavy Armor T1', 'aburrey_legacy', 4, 'Agility', 61, 'Strength', 41, 'Combo Skill DMG Bonus %', 14.7, 40, 'assets/gear/aburrey_heavy_armor_t1.png'),
    ('aburrey_legacy_armor', 'armor', 'Aburrey Light Armor', 'aburrey_legacy', 4, 'Intellect', 61, 'Strength', 41, 'Ultimate Gain Efficiency %', 8.8, 40, 'assets/gear/aburrey_legacy_armor.png'),
    ('aburrey_light_armor_t1', 'armor', 'Aburrey Light Armor T1', 'aburrey_legacy', 4, 'Will', 61, 'Agility', 41, 'Battle Skill DMG Bonus %', 14.7, 40, 'assets/gear/aburrey_light_armor_t1.png'),
    ('armored_msgr_jacket_t1', 'armor', 'Armored MSGR Jacket T1', 'armored_msgr', 4, 'Strength', 61, 'Will', 41, 'HP Bonus %', 14.7, 40, 'assets/gear/armored_msgr_jacket_t1.png'),
    ('catastrophe_armor', 'armor', 'Catastrophe Heavy Armor', 'catastrophe', 4, 'Strength', 61, 'Intellect', 41, 'Ultimate DMG Bonus %', 18.4, 40, 'assets/gear/catastrophe_armor.png'),
    ('catastrophe_heavy_armor_t1', 'armor', 'Catastrophe Heavy Armor T1', 'catastrophe', 4, 'Strength', 61, 'Will', 41, 'Ultimate Gain Efficiency %', 8.8, 40, 'assets/gear/catastrophe_heavy_armor_t1.png'),
    ('miner_armor_t1', 'armor', 'Miner Armor T1', null, 4, 'Strength', 65, 'Will', 43, 'Crit Rate %', 3.9, 40, 'assets/gear/miner_armor_t1.png'),
    ('miner_overalls_t1', 'armor', 'Miner Overalls T1', null, 4, 'Intellect', 65, 'Agility', 43, 'Attack', 7.8, 40, 'assets/gear/miner_overalls_t1.png'),
    ('mordvolt_insulation_vest_t1', 'armor', 'Mordvolt Insulation Vest T1', 'mordvolt_insulation', 4, 'Intellect', 61, 'Agility', 41, 'Basic Attack DMG Bonus %', 9.8, 40, 'assets/gear/mordvolt_insulation_vest_t1.png'),
    ('mordvolt_insulation_vest_t2', 'armor', 'Mordvolt Insulation Vest T2', 'mordvolt_insulation', 4, 'Intellect', 61, 'Will', 41, 'HP Bonus %', 14.7, 40, 'assets/gear/mordvolt_insulation_vest_t2.png'),
    ('mordvolt_resistant_vest_t1', 'armor', 'Mordvolt Resistant Vest T1', 'mordvolt_resistant', 4, 'Will', 61, 'Intellect', 41, 'HP Bonus %', 14.7, 40, 'assets/gear/mordvolt_resistant_vest_t1.png'),
    ('roving_msgr_jacket_t1', 'armor', 'Roving MSGR Jacket T1', 'roving_msgr', 4, 'Agility', 61, 'Intellect', 41, 'HP Bonus %', 14.7, 40, 'assets/gear/roving_msgr_jacket_t1.png'),
    ('armored_msgr_armor', 'armor', 'Armored MSGR Jacket', 'armored_msgr', 3, 'Strength', 44, 'Agility', 29, 'HP Bonus %', 10.5, 28.8, 'assets/gear/armored_msgr_armor.png'),
    ('mordvolt_insulation_armor', 'armor', 'Mordvolt Insulation Vest', 'mordvolt_insulation', 3, 'Intellect', 44, 'Strength', 29, 'Attack', 16.2, 28.8, 'assets/gear/mordvolt_insulation_armor.png'),
    ('mordvolt_resistant_armor', 'armor', 'Mordvolt Resistant Vest', 'mordvolt_resistant', 3, 'Will', 44, 'Agility', 29, 'HP Bonus %', 10.5, 28.8, 'assets/gear/mordvolt_resistant_armor.png'),
    ('roving_msgr_armor', 'armor', 'Roving MSGR Jacket', 'roving_msgr', 3, 'Agility', 44, 'Intellect', 29, 'Attack', 16.2, 28.8, 'assets/gear/roving_msgr_armor.png'),
    ('aic_heavy_armor', 'armor', 'AIC Heavy Armor', 'aic_heavy', 2, 'Strength', 30, 'Agility', 30, 'Final DMG Reduction %', 3.9, 22.4, 'assets/gear/aic_heavy_armor.png'),
    ('aic_light_armor', 'armor', 'AIC Light Armor', 'aic_light', 2, 'Intellect', 30, 'Will', 30, 'Battle Skill DMG Bonus %', 8.1, 22.4, 'assets/gear/aic_light_armor.png'),
    ('miner_armor', 'armor', 'Miner Armor', null, 2, 'Strength', 27, 'Agility', 18, 'HP Bonus %', 125.4, 16, 'assets/gear/miner_armor.png'),
    ('miner_cleansuit', 'armor', 'Miner Cleansuit', null, 2, 'Will', 37, 'Agility', 25, 'HP Bonus %', 9, 22.4, 'assets/gear/miner_cleansuit.png'),
    ('miner_overalls', 'armor', 'Miner Overalls', null, 2, 'Intellect', 27, 'Will', 18, 'HP Bonus %', 125.4, 16, 'assets/gear/miner_overalls.png'),
    ('miner_vest', 'armor', 'Miner Vest', null, 2, 'Agility', 37, 'Intellect', 25, 'HP Bonus %', 9, 22.4, 'assets/gear/miner_vest.png'),
    ('prototype_heavy_armor', 'armor', 'Prototype Heavy Armor', null, 2, 'Strength', 37, 'Intellect', 25, 'Attack', 11.7, 22.4, 'assets/gear/prototype_heavy_armor.png'),
    ('prototype_heavy_armor_t1', 'armor', 'Prototype Heavy Armor T1', null, 2, 'Agility', 37, 'Will', 25, 'Attack', 11.7, 22.4, 'assets/gear/prototype_heavy_armor_t1.png'),
    ('basic_armor', 'armor', 'Basic Armor', null, 1, 'Strength', 15, 'Agility', 10, 'HP Bonus %', 46.3, 8, 'assets/gear/basic_armor.png'),
    ('basic_ppe', 'armor', 'Basic PPE', null, 1, 'Intellect', 15, 'Will', 10, 'HP Bonus %', 46.3, 8, 'assets/gear/basic_ppe.png'),
    ('aic_fieldwork_gloves', 'gloves', 'AIC Fieldwork Gloves', 'aic_fieldwork', 5, 'Main Attribute', 55, 'Secondary Attribute', 37, 'Arts DMG Dealt Bonus %', 15.5, 36, 'assets/gear/aic_fieldwork_gloves.png'),
    ('aic_fieldwork_hands', 'gloves', 'AIC Fieldwork Hands', 'aic_fieldwork', 5, 'Main Attribute', 55, 'Secondary Attribute', 37, 'Ultimate Gain Efficiency %', 17.6, 36, 'assets/gear/aic_fieldwork_hands.png'),
    ('aic_fieldwork_wraps', 'gloves', 'AIC Fieldwork Wraps', 'aic_fieldwork', 5, 'Secondary Attribute', 55, 'Main Attribute', 37, 'Secondary Attribute', 14.8, 36, 'assets/gear/aic_fieldwork_wraps.png'),
    ('bonekrusha_gloves', 'gloves', 'Bonekrusha Gloves', 'bonekrusha', 5, 'Will', 65, 'Agility', 43, 'Cryo and Electric DMG Dealt Bonus %', 19.2, 42, 'assets/gear/bonekrusha_gloves.png'),
    ('bonekrusha_wristband', 'gloves', 'Bonekrusha Wristband', 'bonekrusha', 5, 'Strength', 65, 'Agility', 43, 'Heat and Nature DMG Dealt Bonus %', 19.2, 42, 'assets/gear/bonekrusha_wristband.png'),
    ('bonekrusha_wristband_t1', 'gloves', 'Bonekrusha Wristband T1', 'bonekrusha', 5, 'Agility', 65, 'Strength', 43, 'Cryo and Electric DMG Dealt Bonus %', 19.2, 42, 'assets/gear/bonekrusha_wristband_t1.png'),
    ('eternal_xiranite_gloves', 'gloves', 'Eternal Xiranite Gloves', 'eternal_xiranite', 5, 'Intellect', 65, 'Strength', 43, 'Ultimate Gain Efficiency %', 20.5, 42, 'assets/gear/eternal_xiranite_gloves.png'),
    ('eternal_xiranite_gloves_t1', 'gloves', 'Eternal Xiranite Gloves T1', 'eternal_xiranite', 5, 'Intellect', 65, 'Will', 43, 'Ultimate Gain Efficiency %', 20.5, 42, 'assets/gear/eternal_xiranite_gloves_t1.png'),
    ('eternal_xiranite_hands', 'gloves', 'Eternal Xiranite Hands', 'eternal_xiranite', 5, 'Will', 65, 'Agility', 43, 'Ultimate Gain Efficiency %', 20.5, 42, 'assets/gear/eternal_xiranite_hands.png'),
    ('eternal_xiranite_wraps', 'gloves', 'Eternal Xiranite Wraps', 'eternal_xiranite', 5, 'Will', 65, 'Intellect', 43, 'Ultimate Gain Efficiency %', 20.5, 42, 'assets/gear/eternal_xiranite_wraps.png'),
    ('frontiers_gloves', 'gloves', 'Frontiers Blight RES Gloves', 'frontiers', 5, 'Agility', 65, 'Intellect', 43, 'Battle Skill DMG Bonus %', 34.5, 42, 'assets/gear/frontiers_gloves.png'),
    ('frontiers_fiber_gloves', 'gloves', 'Frontiers Fiber Gloves', 'frontiers', 5, 'Will', 65, 'Strength', 43, 'Skill DMG Bonus %', 23, 42, 'assets/gear/frontiers_fiber_gloves.png'),
    ('frontiers_fiber_gloves_t1', 'gloves', 'Frontiers Fiber Gloves T1', 'frontiers', 5, 'Intellect', 65, 'Agility', 43, 'Ultimate Gain Efficiency %', 20.5, 42, 'assets/gear/frontiers_fiber_gloves_t1.png'),
    ('grizzled_edge_gauntlets', 'gloves', 'Grizzled Edge Gauntlets', 'grizzled_edge', 5, 'Strength', 65, 'Will', 43, 'Arts Intensity', 34.5, 42, 'assets/gear/grizzled_edge_gauntlets.png'),
    ('grizzled_edge_gauntlets_t1', 'gloves', 'Grizzled Edge Gauntlets T1', 'grizzled_edge', 5, 'Agility', 65, 'Strength', 43, 'Arts Intensity', 34.5, 42, 'assets/gear/grizzled_edge_gauntlets_t1.png'),
    ('hot_work_gloves', 'gloves', 'Hot Work Gauntlets', 'hot_work', 5, 'Intellect', 65, 'Strength', 43, 'Heat and Nature DMG Dealt Bonus %', 19.2, 42, 'assets/gear/hot_work_gloves.png'),
    ('hot_work_gauntlets_t1', 'gloves', 'Hot Work Gauntlets T1', 'hot_work', 5, 'Will', 65, 'Intellect', 43, 'Heat and Nature DMG Dealt Bonus %', 19.2, 42, 'assets/gear/hot_work_gauntlets_t1.png'),
    ('hot_work_gloves_variant', 'gloves', 'Hot Work Gloves', 'hot_work', 5, 'Strength', 65, 'Will', 43, 'Arts Intensity', 34.5, 42, 'assets/gear/hot_work_gloves_variant.png'),
    ('hot_work_hands_ppe', 'gloves', 'Hot Work Hands PPE', 'hot_work', 5, 'Intellect', 65, 'Will', 43, 'Heat and Nature DMG Dealt Bonus %', 19.2, 42, 'assets/gear/hot_work_hands_ppe.png'),
    ('lynx_gauntlets', 'gloves', 'LYNX Gauntlets', 'lynx', 5, 'Will', 65, 'Strength', 43, 'Treatment Effect %', 17.2, 42, 'assets/gear/lynx_gauntlets.png'),
    ('lynx_gauntlets_t1', 'gloves', 'LYNX Gauntlets T1', 'lynx', 5, 'Will', 65, 'Agility', 43, 'Ultimate Gain Efficiency %', 20.5, 42, 'assets/gear/lynx_gauntlets_t1.png'),
    ('lynx_gloves', 'gloves', 'LYNX Gloves', 'lynx', 5, 'Strength', 65, 'Will', 43, 'Ultimate Gain Efficiency %', 20.5, 42, 'assets/gear/lynx_gloves.png'),
    ('mi_security_gloves', 'gloves', 'MI Security Gloves', 'mi_security', 5, 'Agility', 65, 'Strength', 43, 'Battle Skill DMG Bonus %', 34.5, 42, 'assets/gear/mi_security_gloves.png'),
    ('mi_security_gloves_t1', 'gloves', 'MI Security Gloves T1', 'mi_security', 5, 'Agility', 65, 'Intellect', 43, 'Ultimate DMG Bonus %', 43.1, 42, 'assets/gear/mi_security_gloves_t1.png'),
    ('mi_security_hands_ppe', 'gloves', 'MI Security Hands PPE', 'mi_security', 5, 'Intellect', 65, 'Agility', 43, 'Basic Attack DMG Bonus %', 23, 42, 'assets/gear/mi_security_hands_ppe.png'),
    ('mi_security_hands_ppe_t1', 'gloves', 'MI Security Hands PPE T1', 'mi_security', 5, 'Intellect', 65, 'Will', 43, 'Crit Rate %', 8.6, 42, 'assets/gear/mi_security_hands_ppe_t1.png'),
    ('pulser_labs_gloves', 'gloves', 'Pulser Labs Gloves', 'pulser_labs', 5, 'Will', 65, 'Intellect', 43, 'Cryo and Electric DMG Dealt Bonus %', 19.2, 42, 'assets/gear/pulser_labs_gloves.png'),
    ('qingbo_gauntlets', 'gloves', 'Qingbo Gauntlets', 'qingbo', 5, 'Agility', 65, 'Strength', 43, 'Skill DMG Bonus %', 23, 42, 'assets/gear/qingbo_gauntlets.png'),
    ('qingbo_gloves', 'gloves', 'Qingbo Gloves', 'qingbo', 5, 'Intellect', 65, 'Will', 43, 'Ultimate Gain Efficiency %', 20.5, 42, 'assets/gear/qingbo_gloves.png'),
    ('redeemer_gloves', 'gloves', 'Redeemer Gloves', null, 5, 'Agility', 86, null, null, 'Ultimate DMG Bonus %', 45, 42, 'assets/gear/redeemer_gloves.png'),
    ('redeemer_hands', 'gloves', 'Redeemer Hands', null, 5, 'Strength', 86, null, null, 'Skill DMG Bonus %', 24, 42, 'assets/gear/redeemer_hands.png'),
    ('rift_trekker_gloves', 'gloves', 'Rift Trekker Gloves', null, 5, 'Intellect', 86, null, null, 'Ultimate Gain Efficiency %', 21.4, 42, 'assets/gear/rift_trekker_gloves.png'),
    ('rift_trekker_hands', 'gloves', 'Rift Trekker Hands', null, 5, 'Will', 86, null, null, 'Battle Skill DMG Bonus %', 36, 42, 'assets/gear/rift_trekker_hands.png'),
    ('swordmancer_gloves', 'gloves', 'Swordmancer TAC Gauntlets', 'swordmancer', 5, 'Agility', 65, 'Strength', 43, 'Ultimate DMG Bonus %', 43.1, 42, 'assets/gear/swordmancer_gloves.png'),
    ('swordmancer_tac_gauntlets_t1', 'gloves', 'Swordmancer TAC Gauntlets T1', 'swordmancer', 5, 'Strength', 65, 'Will', 43, 'Arts Intensity', 34.5, 42, 'assets/gear/swordmancer_tac_gauntlets_t1.png'),
    ('swordmancer_tac_gloves', 'gloves', 'Swordmancer TAC Gloves', 'swordmancer', 5, 'Strength', 65, 'Will', 43, 'Physical DMG Bonus %', 19.2, 42, 'assets/gear/swordmancer_tac_gloves.png'),
    ('tide_surge_gloves', 'gloves', 'Tide Surge Gauntlets', 'tide_surge', 5, 'Strength', 65, 'Will', 43, 'Cryo and Electric DMG Dealt Bonus %', 19.2, 42, 'assets/gear/tide_surge_gloves.png'),
    ('type_50_yinglung_gloves', 'gloves', 'Type 50 Yinglung Gloves', 'type_50_yinglung', 5, 'Agility', 65, 'Intellect', 43, 'Combo Skill DMG Bonus %', 34.5, 42, 'assets/gear/type_50_yinglung_gloves.png'),
    ('type_50_yinglung_gloves_t1', 'gloves', 'Type 50 Yinglung Gloves T1', 'type_50_yinglung', 5, 'Will', 65, 'Agility', 43, 'Combo Skill DMG Bonus %', 34.5, 42, 'assets/gear/type_50_yinglung_gloves_t1.png'),
    ('xiranflow_gloves', 'gloves', 'Xiranflow Gloves', 'xiranflow', 5, 'Will', 65, 'Intellect', 43, 'Cryo and Electric DMG Dealt Bonus %', 19.2, 42, 'assets/gear/xiranflow_gloves.png'),
    ('aethertech_gloves', 'gloves', 'Æthertech Gloves', 'aethertech', 5, 'Agility', 65, 'Strength', 43, 'Arts Intensity', 34.5, 42, 'assets/gear/aethertech_gloves.png'),
    ('aethertech_light_gloves', 'gloves', 'Æthertech Light Gloves', 'aethertech', 5, 'Will', 65, 'Agility', 43, 'Skill DMG Bonus %', 23, 42, 'assets/gear/aethertech_light_gloves.png'),
    ('aburrey_legacy_gloves', 'gloves', 'Aburrey Gauntlets', 'aburrey_legacy', 4, 'Strength', 46, 'Will', 30, 'DMG Bonus vs. Staggered', 24.5, 30, 'assets/gear/aburrey_legacy_gloves.png'),
    ('armored_msgr_gloves_t1', 'gloves', 'Armored MSGR Gloves T1', 'armored_msgr', 4, 'Strength', 46, 'Agility', 30, 'Attack', 12.2, 30, 'assets/gear/armored_msgr_gloves_t1.png'),
    ('armored_msgr_gloves_t2', 'gloves', 'Armored MSGR Gloves T2', 'armored_msgr', 4, 'Strength', 46, 'Agility', 30, 'Combo Skill DMG Bonus %', 24.5, 30, 'assets/gear/armored_msgr_gloves_t2.png'),
    ('catastrophe_gloves', 'gloves', 'Catastrophe Gloves', 'catastrophe', 4, 'Will', 46, 'Intellect', 30, 'Arts Intensity', 24.5, 30, 'assets/gear/catastrophe_gloves.png'),
    ('miner_fists_t1', 'gloves', 'Miner Fists T1', null, 4, 'Will', 49, 'Intellect', 32, 'Ultimate Gain Efficiency %', 15.5, 30, 'assets/gear/miner_fists_t1.png'),
    ('miner_gloves_t2', 'gloves', 'Miner Gloves T2', null, 4, 'Intellect', 49, 'Agility', 32, 'Attack', 13, 30, 'assets/gear/miner_gloves_t2.png'),
    ('mordvolt_insulation_gloves_t1', 'gloves', 'Mordvolt Insulation Gloves T1', 'mordvolt_insulation', 4, 'Intellect', 46, 'Strength', 30, 'Attack', 12.2, 30, 'assets/gear/mordvolt_insulation_gloves_t1.png'),
    ('mordvolt_resistant_gloves_t1', 'gloves', 'Mordvolt Resistant Gloves T1', 'mordvolt_resistant', 4, 'Will', 46, 'Agility', 30, 'Attack', 12.2, 30, 'assets/gear/mordvolt_resistant_gloves_t1.png'),
    ('roving_msgr_fists_t1', 'gloves', 'Roving MSGR Fists T1', 'roving_msgr', 4, 'Agility', 46, 'Strength', 30, 'Attack', 12.2, 30, 'assets/gear/roving_msgr_fists_t1.png'),
    ('armored_msgr_gloves', 'gloves', 'Armored MSGR Gloves', 'armored_msgr', 3, 'Strength', 33, 'Will', 22, 'Final DMG Reduction %', 8, 21.6, 'assets/gear/armored_msgr_gloves.png'),
    ('miner_gauntlets_t1', 'gloves', 'Miner Gauntlets T1', null, 3, 'Strength', 36, 'Intellect', 24, 'Attack', 9.5, 21.6, 'assets/gear/miner_gauntlets_t1.png'),
    ('miner_gloves_t1', 'gloves', 'Miner Gloves T1', null, 3, 'Intellect', 36, 'Agility', 24, 'HP Bonus %', 19, 21.6, 'assets/gear/miner_gloves_t1.png'),
    ('mordvolt_insulation_gloves', 'gloves', 'Mordvolt Insulation Gloves', 'mordvolt_insulation', 3, 'Intellect', 33, 'Will', 22, 'Arts DMG Dealt Bonus %', 9.2, 21.6, 'assets/gear/mordvolt_insulation_gloves.png'),
    ('mordvolt_resistant_gloves', 'gloves', 'Mordvolt Resistant Gloves', 'mordvolt_resistant', 3, 'Will', 33, 'Intellect', 22, 'Treatment Effect %', 8.8, 21.6, 'assets/gear/mordvolt_resistant_gloves.png'),
    ('roving_msgr_gloves', 'gloves', 'Roving MSGR Fists', 'roving_msgr', 3, 'Agility', 33, 'Strength', 22, 'Physical DMG Bonus %', 9.7, 21.6, 'assets/gear/roving_msgr_gloves.png'),
    ('aic_heavy_gloves', 'gloves', 'AIC Gauntlets', 'aic_heavy', 2, 'Strength', 23, 'Will', 23, 'Final DMG Reduction %', 6.3, 16.8, 'assets/gear/aic_heavy_gloves.png'),
    ('aic_light_gloves', 'gloves', 'AIC Tactical Gloves', 'aic_light', 2, 'Intellect', 23, 'Agility', 23, 'Combo Skill DMG Bonus %', 13.5, 16.8, 'assets/gear/aic_light_gloves.png'),
    ('miner_fists', 'gloves', 'Miner Fists', null, 2, 'Will', 28, 'Intellect', 18, 'HP Bonus %', 15, 16.8, 'assets/gear/miner_fists.png'),
    ('miner_gauntlets', 'gloves', 'Miner Gauntlets', null, 2, 'Strength', 20, 'Agility', 13, 'HP Bonus %', 11, 12, 'assets/gear/miner_gauntlets.png'),
    ('miner_gloves', 'gloves', 'Miner Gloves', null, 2, 'Intellect', 20, 'Will', 13, 'HP Bonus %', 11, 12, 'assets/gear/miner_gloves.png'),
    ('miner_wrists', 'gloves', 'Miner Wrists', null, 2, 'Agility', 28, 'Strength', 18, 'HP Bonus %', 15, 16.8, 'assets/gear/miner_wrists.png'),
    ('basic_gauntlets', 'gloves', 'Basic Gauntlets', null, 1, 'Strength', 11, 'Agility', 7, 'HP Bonus %', 77.2, 6, 'assets/gear/basic_gauntlets.png'),
    ('basic_gloves', 'gloves', 'Basic Gloves', null, 1, 'Intellect', 11, 'Will', 7, 'HP Bonus %', 77.2, 6, 'assets/gear/basic_gloves.png'),
    ('aic_fieldwork_ember', 'kits', 'AIC Fieldwork Ember', 'aic_fieldwork', 5, 'Main Attribute', 27, 'Secondary Attribute', 18, 'Ultimate Gain Efficiency %', 21.1, 18, 'assets/gear/aic_fieldwork_ember.png'),
    ('aic_fieldwork_flashlight', 'kits', 'AIC Fieldwork Flashlight', 'aic_fieldwork', 5, 'Secondary Attribute', 27, 'Main Attribute', 18, 'Secondary Attribute', 17.7, 18, 'assets/gear/aic_fieldwork_flashlight.png'),
    ('aic_fieldwork_machete', 'kits', 'AIC Fieldwork Machete', 'aic_fieldwork', 5, 'Main Attribute', 27, 'Secondary Attribute', 18, 'Arts DMG Dealt Bonus %', 18.6, 18, 'assets/gear/aic_fieldwork_machete.png'),
    ('bonekrusha_kit', 'kits', 'Bonekrusha Figurine', 'bonekrusha', 5, 'Will', 32, 'Agility', 21, 'Battle Skill DMG Bonus %', 41.4, 21, 'assets/gear/bonekrusha_kit.png'),
    ('bonekrusha_figurine_t1', 'kits', 'Bonekrusha Figurine T1', 'bonekrusha', 5, 'Will', 32, 'Intellect', 21, 'Combo Skill DMG Bonus %', 41.4, 21, 'assets/gear/bonekrusha_figurine_t1.png'),
    ('bonekrusha_figurine_t2', 'kits', 'Bonekrusha Figurine T2', 'bonekrusha', 5, 'Will', 32, 'Intellect', 21, 'Battle Skill DMG Bonus %', 41.4, 21, 'assets/gear/bonekrusha_figurine_t2.png'),
    ('bonekrusha_mask_kit', 'kits', 'Bonekrusha Mask', 'bonekrusha', 5, 'Agility', 32, 'Strength', 21, 'DMG Bonus vs. Staggered', 41.4, 21, 'assets/gear/bonekrusha_mask_kit.png'),
    ('bonekrusha_mask_t1', 'kits', 'Bonekrusha Mask T1', 'bonekrusha', 5, 'Agility', 32, 'Strength', 21, 'Crit Rate %', 10.3, 21, 'assets/gear/bonekrusha_mask_t1.png'),
    ('bonekrusha_mask_t2', 'kits', 'Bonekrusha Mask T2', 'bonekrusha', 5, 'Agility', 32, 'Strength', 21, 'Battle Skill DMG Bonus %', 41.4, 21, 'assets/gear/bonekrusha_mask_t2.png'),
    ('eternal_xiranite_auxiliary_arm_kit', 'kits', 'Eternal Xiranite Auxiliary Arm', 'eternal_xiranite', 5, 'Will', 32, 'Intellect', 21, 'Ultimate Gain Efficiency %', 24.6, 21, 'assets/gear/eternal_xiranite_auxiliary_arm_kit.png'),
    ('eternal_xiranite_bracing_slab', 'kits', 'Eternal Xiranite Bracing Slab', 'eternal_xiranite', 5, 'Will', 41, 'Secondary Attribute', 20.7, 'Defense', 21, 21, 'assets/gear/eternal_xiranite_bracing_slab.png'),
    ('eternal_xiranite_kit', 'kits', 'Eternal Xiranite Power Core', 'eternal_xiranite', 5, 'Intellect', 32, 'Strength', 21, 'Ultimate Gain Efficiency %', 24.6, 21, 'assets/gear/eternal_xiranite_kit.png'),
    ('eternal_xiranite_power_core_t1', 'kits', 'Eternal Xiranite Power Core T1', 'eternal_xiranite', 5, 'Intellect', 32, 'Will', 21, 'Treatment Effect %', 20.7, 21, 'assets/gear/eternal_xiranite_power_core_t1.png'),
    ('frontiers_analyzer', 'kits', 'Frontiers Analyzer', 'frontiers', 5, 'Strength', 41, null, null, 'Ultimate DMG Bonus %', 51.7, 21, 'assets/gear/frontiers_analyzer.png'),
    ('frontiers_kit', 'kits', 'Frontiers Comm', 'frontiers', 5, 'Strength', 32, 'Agility', 21, 'Combo Skill DMG Bonus %', 41.4, 21, 'assets/gear/frontiers_kit.png'),
    ('frontiers_comm_t1', 'kits', 'Frontiers Comm T1', 'frontiers', 5, 'Strength', 32, 'Intellect', 21, 'Cryo and Electric DMG Dealt Bonus %', 23, 21, 'assets/gear/frontiers_comm_t1.png'),
    ('frontiers_extra_o2_tube_kit', 'kits', 'Frontiers Extra O2 Tube', 'frontiers', 5, 'Agility', 32, 'Intellect', 21, 'Secondary Attribute', 20.7, 21, 'assets/gear/frontiers_extra_o2_tube_kit.png'),
    ('frontiers_extra_o2_tube_t1', 'kits', 'Frontiers Extra O2 Tube T1', 'frontiers', 5, 'Intellect', 32, 'Agility', 21, 'Secondary Attribute', 20.7, 21, 'assets/gear/frontiers_extra_o2_tube_t1.png'),
    ('frontiers_o2_tube', 'kits', 'Frontiers O2 Tube', 'frontiers', 5, 'Will', 41, null, null, 'Physical DMG Bonus %', 23, 21, 'assets/gear/frontiers_o2_tube.png'),
    ('grizzled_edge_push_knife', 'kits', 'Grizzled Edge Push Knife', 'grizzled_edge', 5, 'Strength', 32, 'Will', 21, 'Physical DMG Bonus %', 23, 21, 'assets/gear/grizzled_edge_push_knife.png'),
    ('grizzled_edge_push_knife_t1', 'kits', 'Grizzled Edge Push Knife T1', 'grizzled_edge', 5, 'Agility', 32, 'Strength', 21, 'Physical DMG Bonus %', 23, 21, 'assets/gear/grizzled_edge_push_knife_t1.png'),
    ('tide_surge_kit', 'kits', 'Hanging River O2 Tube', 'tide_surge', 5, 'Strength', 32, 'Will', 21, 'Cryo and Electric DMG Dealt Bonus %', 23, 21, 'assets/gear/tide_surge_kit.png'),
    ('hot_work_insulation_slab', 'kits', 'Hot Work Insulation Slab', 'hot_work', 5, 'Intellect', 32, 'Will', 21, 'Skill DMG Bonus %', 27.6, 21, 'assets/gear/hot_work_insulation_slab.png'),
    ('hot_work_kit', 'kits', 'Hot Work Power Bank', 'hot_work', 5, 'Strength', 32, 'Agility', 21, 'Arts Intensity', 41.4, 21, 'assets/gear/hot_work_kit.png'),
    ('hot_work_power_cartridge_kit', 'kits', 'Hot Work Power Cartridge', 'hot_work', 5, 'Will', 32, 'Intellect', 21, 'Arts Intensity', 41.4, 21, 'assets/gear/hot_work_power_cartridge_kit.png'),
    ('hot_work_pyrometer_kit', 'kits', 'Hot Work Pyrometer', 'hot_work', 5, 'Intellect', 41, null, null, 'Battle Skill DMG Bonus %', 41.4, 21, 'assets/gear/hot_work_pyrometer_kit.png'),
    ('lynx_aegis_injector_kit', 'kits', 'LYNX Aegis Injector', 'lynx', 5, 'Will', 41, null, null, 'Treatment Effect %', 20.7, 21, 'assets/gear/lynx_aegis_injector_kit.png'),
    ('lynx_kit', 'kits', 'LYNX Connector', 'lynx', 5, 'Strength', 32, 'Will', 21, 'Final DMG Reduction %', 17.1, 21, 'assets/gear/lynx_kit.png'),
    ('lynx_connector_t1', 'kits', 'LYNX Connector T1', 'lynx', 5, 'Strength', 32, 'Will', 21, 'HP Bonus %', 41.4, 21, 'assets/gear/lynx_connector_t1.png'),
    ('lynx_connector_t2', 'kits', 'LYNX Connector T2', 'lynx', 5, 'Strength', 41, null, null, 'HP Bonus %', 41.4, 21, 'assets/gear/lynx_connector_t2.png'),
    ('lynx_slab_kit', 'kits', 'LYNX Slab', 'lynx', 5, 'Will', 32, 'Intellect', 21, 'Main Attribute', 20.7, 21, 'assets/gear/lynx_slab_kit.png'),
    ('mi_security_armband_kit', 'kits', 'MI Security Armband', 'mi_security', 5, 'Strength', 32, 'Will', 21, 'Cryo and Electric DMG Dealt Bonus %', 23, 21, 'assets/gear/mi_security_armband_kit.png'),
    ('mi_security_push_knife_kit', 'kits', 'MI Security Push Knife', 'mi_security', 5, 'Will', 32, 'Intellect', 21, 'Heat and Nature DMG Dealt Bonus %', 23, 21, 'assets/gear/mi_security_push_knife_kit.png'),
    ('mi_security_push_knife_t1', 'kits', 'MI Security Push Knife T1', 'mi_security', 5, 'Will', 32, 'Agility', 21, 'Battle Skill DMG Bonus %', 41.4, 21, 'assets/gear/mi_security_push_knife_t1.png'),
    ('mi_security_scope_kit', 'kits', 'MI Security Scope', 'mi_security', 5, 'Agility', 32, 'Strength', 21, 'Battle Skill DMG Bonus %', 41.4, 21, 'assets/gear/mi_security_scope_kit.png'),
    ('mi_security_scope_t1', 'kits', 'MI Security Scope T1', 'mi_security', 5, 'Agility', 32, 'Intellect', 21, 'Crit Rate %', 10.3, 21, 'assets/gear/mi_security_scope_t1.png'),
    ('mi_security_kit', 'kits', 'MI Security Toolkit', 'mi_security', 5, 'Intellect', 32, 'Agility', 21, 'Crit Rate %', 10.3, 21, 'assets/gear/mi_security_kit.png'),
    ('pulser_labs_kit', 'kits', 'Pulser Labs Calibrator', 'pulser_labs', 5, 'Intellect', 41, null, null, 'Arts Intensity', 41.4, 21, 'assets/gear/pulser_labs_kit.png'),
    ('pulser_labs_invasion_core', 'kits', 'Pulser Labs Invasion Core', 'pulser_labs', 5, 'Will', 41, null, null, 'Ultimate DMG Bonus %', 51.7, 21, 'assets/gear/pulser_labs_invasion_core.png'),
    ('pulser_labs_probe', 'kits', 'Pulser Labs Probe', 'pulser_labs', 5, 'Intellect', 32, 'Agility', 21, 'Arts Intensity', 41.4, 21, 'assets/gear/pulser_labs_probe.png'),
    ('qingbo_bamboo_cutter', 'kits', 'Qingbo Bamboo Cutter', 'qingbo', 5, 'Strength', 32, 'Agility', 21, 'Heat and Nature DMG Dealt Bonus %', 23, 21, 'assets/gear/qingbo_bamboo_cutter.png'),
    ('qingbo_cask', 'kits', 'Qingbo Cask', 'qingbo', 5, 'Intellect', 32, 'Will', 21, 'Arts Intensity', 41.4, 21, 'assets/gear/qingbo_cask.png'),
    ('qingbo_positioning_kit', 'kits', 'Qingbo Positioning Kit', 'qingbo', 5, 'Agility', 32, 'Strength', 21, 'Battle Skill DMG Bonus %', 41.4, 21, 'assets/gear/qingbo_positioning_kit.png'),
    ('qingbo_positioning_kit_t1', 'kits', 'Qingbo Positioning Kit T1', 'qingbo', 5, 'Agility', 32, 'Strength', 21, 'Physical DMG Bonus %', 23, 21, 'assets/gear/qingbo_positioning_kit_t1.png'),
    ('redeemer_seal', 'kits', 'Redeemer Seal', null, 5, 'Intellect', 43, null, null, 'Ultimate Gain Efficiency %', 25.7, 21, 'assets/gear/redeemer_seal.png'),
    ('redeemer_seal_t1', 'kits', 'Redeemer Seal T1', null, 5, 'Will', 43, null, null, 'Crit Rate %', 10.8, 21, 'assets/gear/redeemer_seal_t1.png'),
    ('redeemer_tag', 'kits', 'Redeemer Tag', null, 5, 'Strength', 43, null, null, 'Final DMG Reduction %', 17.8, 21, 'assets/gear/redeemer_tag.png'),
    ('redeemer_tag_t1', 'kits', 'Redeemer Tag T1', null, 5, 'Agility', 43, null, null, 'Combo Skill DMG Bonus %', 43.2, 21, 'assets/gear/redeemer_tag_t1.png'),
    ('rift_trekker_armor_slab', 'kits', 'Rift Trekker Armor Slab', null, 5, 'Agility', 43, 'Secondary Attribute', 21.6, 'Defense', 21, 21, 'assets/gear/rift_trekker_armor_slab.png'),
    ('swordmancer_dagger', 'kits', 'Swordmancer Dagger', 'swordmancer', 5, 'Agility', 32, 'Strength', 21, 'Ultimate DMG Bonus %', 51.7, 21, 'assets/gear/swordmancer_dagger.png'),
    ('swordmancer_kit', 'kits', 'Swordmancer Flint', 'swordmancer', 5, 'Agility', 32, 'Strength', 21, 'Physical DMG Bonus %', 23, 21, 'assets/gear/swordmancer_kit.png'),
    ('swordmancer_micro_filter', 'kits', 'Swordmancer Micro Filter', 'swordmancer', 5, 'Strength', 32, 'Will', 21, 'Physical DMG Bonus %', 23, 21, 'assets/gear/swordmancer_micro_filter.png'),
    ('swordmancer_nav_beacon', 'kits', 'Swordmancer NAV Beacon', 'swordmancer', 5, 'Strength', 41, null, null, 'Arts Intensity', 41.4, 21, 'assets/gear/swordmancer_nav_beacon.png'),
    ('turbid_cutting_torch_kit', 'kits', 'Turbid Cutting Torch', 'tide_surge', 5, 'Intellect', 32, 'Strength', 21, 'Basic Attack DMG Bonus %', 27.6, 21, 'assets/gear/turbid_cutting_torch_kit.png'),
    ('type_50_yinglung_knife_kit', 'kits', 'Type 50 Yinglung Knife', 'type_50_yinglung', 5, 'Will', 32, 'Agility', 21, 'Combo Skill DMG Bonus %', 41.4, 21, 'assets/gear/type_50_yinglung_knife_kit.png'),
    ('type_50_yinglung_knife_t1', 'kits', 'Type 50 Yinglung Knife T1', 'type_50_yinglung', 5, 'Intellect', 32, 'Strength', 21, 'Skill DMG Bonus %', 27.6, 21, 'assets/gear/type_50_yinglung_knife_t1.png'),
    ('type_50_yinglung_kit', 'kits', 'Type 50 Yinglung Radar', 'type_50_yinglung', 5, 'Strength', 32, 'Will', 21, 'Physical DMG Bonus %', 23, 21, 'assets/gear/type_50_yinglung_kit.png'),
    ('type_50_yinglung_radar_t1', 'kits', 'Type 50 Yinglung Radar T1', 'type_50_yinglung', 5, 'Agility', 32, 'Strength', 21, 'Ultimate DMG Bonus %', 51.7, 21, 'assets/gear/type_50_yinglung_radar_t1.png'),
    ('type_50_yinglung_radar_t2', 'kits', 'Type 50 Yinglung Radar T2', 'type_50_yinglung', 5, 'Agility', 32, 'Intellect', 21, 'Combo Skill DMG Bonus %', 41.4, 21, 'assets/gear/type_50_yinglung_radar_t2.png'),
    ('xiranflow_baton', 'kits', 'Xiranflow Baton', 'xiranflow', 5, 'Will', 32, 'Intellect', 21, 'Battle Skill DMG Bonus %', 41.4, 21, 'assets/gear/xiranflow_baton.png'),
    ('Æthertech_analysis_band_kit', 'kits', 'Æthertech Analysis Band', 'aethertech', 5, 'Strength', 32, 'Will', 21, 'Physical DMG Bonus %', 23, 21, 'assets/gear/aethertech_analysis_band.png'),
    ('Æthertech_stabilizer_kit', 'kits', 'Æthertech Stabilizer', 'aethertech', 5, 'Agility', 32, 'Strength', 21, 'Arts Intensity', 41.4, 21, 'assets/gear/aethertech_stabilizer.png'),
    ('aethertech_stabilizer_t1', 'kits', 'Æthertech Stabilizer T1', 'aethertech', 5, 'Agility', 32, 'Strength', 21, 'Physical DMG Bonus %', 23, 21, 'assets/gear/aethertech_stabilizer_t1.png'),
    ('aethertech_watch', 'kits', 'Æthertech Watch', 'aethertech', 5, 'Strength', 32, 'Agility', 21, 'Battle Skill DMG Bonus %', 41.4, 21, 'assets/gear/aethertech_watch.png'),
    ('aburrey_auditory_chip_kit', 'kits', 'Aburrey Auditory Chip', 'aburrey_legacy', 4, 'Strength', 23, 'Will', 15, 'DMG Bonus vs. Staggered', 29.4, 15, 'assets/gear/aburrey_auditory_chip_kit.png'),
    ('aburrey_auditory_chip_t1', 'kits', 'Aburrey Auditory Chip T1', 'aburrey_legacy', 4, 'Agility', 23, 'Strength', 15, 'Combo Skill DMG Bonus %', 29.4, 15, 'assets/gear/aburrey_auditory_chip_t1.png'),
    ('aburrey_flashlight_kit', 'kits', 'Aburrey Flashlight', 'aburrey_legacy', 4, 'Intellect', 23, 'Strength', 15, 'Ultimate Gain Efficiency %', 17.5, 15, 'assets/gear/aburrey_flashlight_kit.png'),
    ('aburrey_sensor_chip_kit', 'kits', 'Aburrey Sensor Chip', 'aburrey_legacy', 4, 'Will', 23, 'Agility', 15, 'Battle Skill DMG Bonus %', 29.4, 15, 'assets/gear/aburrey_sensor_chip_kit.png'),
    ('aburrey_sensor_chip_t1', 'kits', 'Aburrey Sensor Chip T1', 'aburrey_legacy', 4, 'Will', 23, 'Intellect', 15, 'Battle Skill DMG Bonus %', 29.4, 15, 'assets/gear/aburrey_sensor_chip_t1.png'),
    ('aburrey_legacy_kit', 'kits', 'Aburrey UV Lamp', 'aburrey_legacy', 4, 'Strength', 23, 'Agility', 15, 'Skill DMG Bonus %', 19.6, 15, 'assets/gear/aburrey_legacy_kit.png'),
    ('armored_msgr_flashlight_t1', 'kits', 'Armored MSGR Flashlight T1', 'armored_msgr', 4, 'Strength', 23, 'Agility', 15, 'Crit Rate %', 7.3, 15, 'assets/gear/armored_msgr_flashlight_t1.png'),
    ('armored_msgr_gyro_t1', 'kits', 'Armored MSGR Gyro T1', 'armored_msgr', 4, 'Strength', 23, 'Will', 15, 'Attack', 14.7, 15, 'assets/gear/armored_msgr_gyro_t1.png'),
    ('catastrophe_kit', 'kits', 'Catastrophe Filter', 'catastrophe', 4, 'Will', 23, 'Intellect', 15, 'Arts Intensity', 29.4, 15, 'assets/gear/catastrophe_kit.png'),
    ('catastrophe_gauze_cartridge_kit', 'kits', 'Catastrophe Gauze Cartridge', 'catastrophe', 4, 'Strength', 23, 'Intellect', 15, 'Ultimate DMG Bonus %', 36.8, 15, 'assets/gear/catastrophe_gauze_cartridge_kit.png'),
    ('catastrophe_gauze_cartridge_t1', 'kits', 'Catastrophe Gauze Cartridge T1', 'catastrophe', 4, 'Strength', 23, 'Will', 15, 'Secondary Attribute', 14.7, 15, 'assets/gear/catastrophe_gauze_cartridge_t1.png'),
    ('miner_comm_t1', 'kits', 'Miner Comm T1', null, 4, 'Will', 31, null, null, 'Treatment Effect %', 15.6, 15, 'assets/gear/miner_comm_t1.png'),
    ('miner_compression_core_t1', 'kits', 'Miner Compression Core T1', null, 4, 'Intellect', 31, null, null, 'Ultimate Gain Efficiency %', 18.6, 15, 'assets/gear/miner_compression_core_t1.png'),
    ('miner_drive_wheel_t1', 'kits', 'Miner Drive Wheel T1', null, 4, 'Agility', 31, null, null, 'Combo Skill DMG Bonus %', 31.2, 15, 'assets/gear/miner_drive_wheel_t1.png'),
    ('miner_turbine_t1', 'kits', 'Miner Turbine T1', null, 4, 'Strength', 31, null, null, 'Final DMG Reduction %', 13.5, 15, 'assets/gear/miner_turbine_t1.png'),
    ('mordvolt_insulation_battery_t1', 'kits', 'Mordvolt Insulation Battery T1', 'mordvolt_insulation', 4, 'Intellect', 29, null, null, 'Ultimate Gain Efficiency %', 17.5, 15, 'assets/gear/mordvolt_insulation_battery_t1.png'),
    ('mordvolt_insulation_wrench_t2', 'kits', 'Mordvolt Insulation Wrench T2', 'mordvolt_insulation', 4, 'Intellect', 23, 'Agility', 15, 'Attack', 14.7, 15, 'assets/gear/mordvolt_insulation_wrench_t2.png'),
    ('mordvolt_resistant_battery_t1', 'kits', 'Mordvolt Resistant Battery T1', 'mordvolt_resistant', 4, 'Will', 23, 'Agility', 15, 'Treatment Effect %', 14.7, 15, 'assets/gear/mordvolt_resistant_battery_t1.png'),
    ('mordvolt_resistant_wrench_t1', 'kits', 'Mordvolt Resistant Wrench T1', 'mordvolt_resistant', 4, 'Will', 23, 'Intellect', 15, 'Attack', 14.7, 15, 'assets/gear/mordvolt_resistant_wrench_t1.png'),
    ('roving_msgr_flashlight_t1', 'kits', 'Roving MSGR Flashlight T1', 'roving_msgr', 4, 'Agility', 23, 'Strength', 15, 'Combo Skill DMG Bonus %', 29.4, 15, 'assets/gear/roving_msgr_flashlight_t1.png'),
    ('roving_msgr_flashlight_t2', 'kits', 'Roving MSGR Flashlight T2', 'roving_msgr', 4, 'Agility', 23, 'Strength', 15, 'Ultimate DMG Bonus %', 36.8, 15, 'assets/gear/roving_msgr_flashlight_t2.png'),
    ('roving_msgr_gyro_t1', 'kits', 'Roving MSGR Gyro T1', 'roving_msgr', 4, 'Agility', 23, 'Intellect', 15, 'Attack', 14.7, 15, 'assets/gear/roving_msgr_gyro_t1.png'),
    ('armored_msgr_flashlight_kit', 'kits', 'Armored MSGR Flashlight', 'armored_msgr', 3, 'Strength', 21, null, null, 'HP Bonus %', 21, 10.8, 'assets/gear/armored_msgr_flashlight_kit.png'),
    ('armored_msgr_kit', 'kits', 'Armored MSGR Gyro', 'armored_msgr', 3, 'Strength', 21, null, null, 'Attack', 10.5, 10.8, 'assets/gear/armored_msgr_kit.png'),
    ('miner_comm', 'kits', 'Miner Comm', null, 3, 'Will', 22, null, null, 'HP Bonus %', 22.8, 10.8, 'assets/gear/miner_comm.png'),
    ('miner_compression_core', 'kits', 'Miner Compression Core', null, 3, 'Intellect', 22, null, null, 'Crit Rate %', 5.7, 10.8, 'assets/gear/miner_compression_core.png'),
    ('miner_drive_wheel', 'kits', 'Miner Drive Wheel', null, 3, 'Agility', 22, null, null, 'Crit Rate %', 5.7, 10.8, 'assets/gear/miner_drive_wheel.png'),
    ('miner_turbine', 'kits', 'Miner Turbine', null, 3, 'Strength', 22, null, null, 'Combo Skill DMG Bonus %', 22.8, 10.8, 'assets/gear/miner_turbine.png'),
    ('mordvolt_insulation_kit', 'kits', 'Mordvolt Insulation Battery', 'mordvolt_insulation', 3, 'Intellect', 21, null, null, 'Crit Rate %', 5.2, 10.8, 'assets/gear/mordvolt_insulation_kit.png'),
    ('mordvolt_insulation_wrench_kit', 'kits', 'Mordvolt Insulation Wrench', 'mordvolt_insulation', 3, 'Intellect', 21, null, null, 'Attack', 10.5, 10.8, 'assets/gear/mordvolt_insulation_wrench_kit.png'),
    ('mordvolt_insulation_wrench_t1', 'kits', 'Mordvolt Insulation Wrench T1', 'mordvolt_insulation', 3, 'Intellect', 21, null, null, 'Cryo and Electric DMG Dealt Bonus %', 11.7, 10.8, 'assets/gear/mordvolt_insulation_wrench_t1.png'),
    ('mordvolt_resistant_kit', 'kits', 'Mordvolt Resistant Battery', 'mordvolt_resistant', 3, 'Will', 21, null, null, 'Treatment Effect %', 10.5, 10.8, 'assets/gear/mordvolt_resistant_kit.png'),
    ('mordvolt_resistant_wrench_kit', 'kits', 'Mordvolt Resistant Wrench', 'mordvolt_resistant', 3, 'Will', 21, null, null, 'Attack', 10.5, 10.8, 'assets/gear/mordvolt_resistant_wrench_kit.png'),
    ('roving_msgr_flashlight_kit', 'kits', 'Roving MSGR Flashlight', 'roving_msgr', 3, 'Agility', 21, null, null, 'Combo Skill DMG Bonus %', 21, 10.8, 'assets/gear/roving_msgr_flashlight_kit.png'),
    ('roving_msgr_kit', 'kits', 'Roving MSGR Gyro', 'roving_msgr', 3, 'Agility', 21, null, null, 'Attack', 10.5, 10.8, 'assets/gear/roving_msgr_kit.png'),
    ('aic_alloy_plate_kit', 'kits', 'AIC Alloy Plate', 'aic_heavy', 2, 'Agility', 16, null, null, 'Final DMG Reduction %', 7.5, 8.4, 'assets/gear/aic_alloy_plate_kit.png'),
    ('aic_ceramic_plate_kit', 'kits', 'AIC Ceramic Plate', 'aic_light', 2, 'Will', 16, null, null, 'Battle Skill DMG Bonus %', 16.2, 8.4, 'assets/gear/aic_ceramic_plate_kit.png'),
    ('aic_heavy_kit', 'kits', 'AIC Heavy Plate', 'aic_heavy', 2, 'Strength', 16, null, null, 'Final DMG Reduction %', 7.5, 8.4, 'assets/gear/aic_heavy_kit.png'),
    ('aic_light_kit', 'kits', 'AIC Light Plate', 'aic_light', 2, 'Intellect', 16, null, null, 'Combo Skill DMG Bonus %', 16.2, 8.4, 'assets/gear/aic_light_kit.png'),
    ('emergency_comm', 'kits', 'Emergency Comm', null, 2, 'Critical Rate', 6.6, null, null, 'Defense', 6, 6, 'assets/gear/emergency_comm.png'),
    ('emergency_compression_core', 'kits', 'Emergency Compression Core', null, 2, 'Attack', 13.2, null, null, 'Defense', 6, 6, 'assets/gear/emergency_compression_core.png')
on conflict (gear_key) do update set
    category = excluded.category,
    name = excluded.name,
    set_key = excluded.set_key,
    rarity = excluded.rarity,
    main_stat = excluded.main_stat,
    main_value = excluded.main_value,
    sec_stat = excluded.sec_stat,
    sec_value = excluded.sec_value,
    sub_stat = excluded.sub_stat,
    sub_value = excluded.sub_value,
    def_value = excluded.def_value,
    icon = excluded.icon,
    updated_at = now();

-- Remove obsolete catalog entries while retaining the stable keys used by this sync.
delete from public.gear_items where gear_key not in ('aburrey_heavy_armor', 'aburrey_heavy_armor_t1', 'aburrey_legacy_armor', 'aburrey_light_armor_t1', 'aic_fieldwork_armor', 'aic_fieldwork_plate', 'aic_fieldwork_vest', 'aic_heavy_armor', 'aic_light_armor', 'armored_msgr_armor', 'armored_msgr_jacket_t1', 'basic_armor', 'basic_ppe', 'bonekrusha_heavy_armor', 'bonekrusha_heavy_armor_t1', 'bonekrusha_heavy_armor_t2', 'bonekrusha_armor', 'bonekrusha_poncho_t1', 'catastrophe_armor', 'catastrophe_heavy_armor_t1', 'eternal_xiranite_armor', 'eternal_xiranite_light_armor', 'eternal_xiranite_light_armor_t1', 'frontiers_armor', 'frontiers_armor_t1', 'frontiers_armor_t2', 'frontiers_armor_t3', 'frontiers_protection_suit', 'grizzled_edge_armor', 'grizzled_edge_armor_t1', 'hot_work_exo_rig', 'hot_work_armor', 'lynx_cuirass', 'lynx_cuirass_t1', 'lynx_armor', 'mi_security_armor', 'mi_security_armor_t1', 'mi_security_overalls', 'mi_security_overalls_t1', 'mi_security_overalls_t2', 'miner_armor', 'miner_armor_t1', 'miner_cleansuit', 'miner_overalls', 'miner_overalls_t1', 'miner_vest', 'mordvolt_insulation_armor', 'mordvolt_insulation_vest_t1', 'mordvolt_insulation_vest_t2', 'mordvolt_resistant_armor', 'mordvolt_resistant_vest_t1', 'prototype_heavy_armor', 'prototype_heavy_armor_t1', 'pulser_labs_armor', 'qingbo_heavy_armor', 'qingbo_light_armor', 'redeemer_armor', 'redeemer_plates', 'rift_trekker_heavy_armor', 'rift_trekker_light_armor', 'roving_msgr_armor', 'roving_msgr_jacket_t1', 'swordmancer_fiber_armor', 'swordmancer_armor', 'swordmancer_heavy_armor_t1', 'swordmancer_light_armor', 'tide_surge_armor', 'type_50_yinglung_armor', 'type_50_yinglung_heavy_armor_t1', 'type_50_yinglung_heavy_armor_t2', 'type_50_yinglung_light_armor', 'xiranflow_light_armor', 'aethertech_armor', 'aburrey_legacy_gloves', 'aic_fieldwork_gloves', 'aic_fieldwork_hands', 'aic_fieldwork_wraps', 'aic_heavy_gloves', 'aic_light_gloves', 'armored_msgr_gloves', 'armored_msgr_gloves_t1', 'armored_msgr_gloves_t2', 'basic_gauntlets', 'basic_gloves', 'bonekrusha_gloves', 'bonekrusha_wristband', 'bonekrusha_wristband_t1', 'catastrophe_gloves', 'eternal_xiranite_gloves', 'eternal_xiranite_gloves_t1', 'eternal_xiranite_hands', 'eternal_xiranite_wraps', 'frontiers_gloves', 'frontiers_fiber_gloves', 'frontiers_fiber_gloves_t1', 'grizzled_edge_gauntlets', 'grizzled_edge_gauntlets_t1', 'hot_work_gloves', 'hot_work_gauntlets_t1', 'hot_work_gloves_variant', 'hot_work_hands_ppe', 'lynx_gauntlets', 'lynx_gauntlets_t1', 'lynx_gloves', 'mi_security_gloves', 'mi_security_gloves_t1', 'mi_security_hands_ppe', 'mi_security_hands_ppe_t1', 'miner_fists', 'miner_fists_t1', 'miner_gauntlets', 'miner_gauntlets_t1', 'miner_gloves', 'miner_gloves_t1', 'miner_gloves_t2', 'miner_wrists', 'mordvolt_insulation_gloves', 'mordvolt_insulation_gloves_t1', 'mordvolt_resistant_gloves', 'mordvolt_resistant_gloves_t1', 'pulser_labs_gloves', 'qingbo_gauntlets', 'qingbo_gloves', 'redeemer_gloves', 'redeemer_hands', 'rift_trekker_gloves', 'rift_trekker_hands', 'roving_msgr_gloves', 'roving_msgr_fists_t1', 'swordmancer_gloves', 'swordmancer_tac_gauntlets_t1', 'swordmancer_tac_gloves', 'tide_surge_gloves', 'type_50_yinglung_gloves', 'type_50_yinglung_gloves_t1', 'xiranflow_gloves', 'aethertech_gloves', 'aethertech_light_gloves', 'aburrey_auditory_chip_kit', 'aburrey_auditory_chip_t1', 'aburrey_flashlight_kit', 'aburrey_sensor_chip_kit', 'aburrey_sensor_chip_t1', 'aburrey_legacy_kit', 'aic_alloy_plate_kit', 'aic_ceramic_plate_kit', 'aic_fieldwork_ember', 'aic_fieldwork_flashlight', 'aic_fieldwork_machete', 'aic_heavy_kit', 'aic_light_kit', 'armored_msgr_flashlight_kit', 'armored_msgr_flashlight_t1', 'armored_msgr_kit', 'armored_msgr_gyro_t1', 'bonekrusha_kit', 'bonekrusha_figurine_t1', 'bonekrusha_figurine_t2', 'bonekrusha_mask_kit', 'bonekrusha_mask_t1', 'bonekrusha_mask_t2', 'catastrophe_kit', 'catastrophe_gauze_cartridge_kit', 'catastrophe_gauze_cartridge_t1', 'emergency_comm', 'emergency_compression_core', 'eternal_xiranite_auxiliary_arm_kit', 'eternal_xiranite_bracing_slab', 'eternal_xiranite_kit', 'eternal_xiranite_power_core_t1', 'frontiers_analyzer', 'frontiers_kit', 'frontiers_comm_t1', 'frontiers_extra_o2_tube_kit', 'frontiers_extra_o2_tube_t1', 'frontiers_o2_tube', 'grizzled_edge_push_knife', 'grizzled_edge_push_knife_t1', 'tide_surge_kit', 'hot_work_insulation_slab', 'hot_work_kit', 'hot_work_power_cartridge_kit', 'hot_work_pyrometer_kit', 'lynx_aegis_injector_kit', 'lynx_kit', 'lynx_connector_t1', 'lynx_connector_t2', 'lynx_slab_kit', 'mi_security_armband_kit', 'mi_security_push_knife_kit', 'mi_security_push_knife_t1', 'mi_security_scope_kit', 'mi_security_scope_t1', 'mi_security_kit', 'miner_comm', 'miner_comm_t1', 'miner_compression_core', 'miner_compression_core_t1', 'miner_drive_wheel', 'miner_drive_wheel_t1', 'miner_turbine', 'miner_turbine_t1', 'mordvolt_insulation_kit', 'mordvolt_insulation_battery_t1', 'mordvolt_insulation_wrench_kit', 'mordvolt_insulation_wrench_t1', 'mordvolt_insulation_wrench_t2', 'mordvolt_resistant_kit', 'mordvolt_resistant_battery_t1', 'mordvolt_resistant_wrench_kit', 'mordvolt_resistant_wrench_t1', 'pulser_labs_kit', 'pulser_labs_invasion_core', 'pulser_labs_probe', 'qingbo_bamboo_cutter', 'qingbo_cask', 'qingbo_positioning_kit', 'qingbo_positioning_kit_t1', 'redeemer_seal', 'redeemer_seal_t1', 'redeemer_tag', 'redeemer_tag_t1', 'rift_trekker_armor_slab', 'roving_msgr_flashlight_kit', 'roving_msgr_flashlight_t1', 'roving_msgr_flashlight_t2', 'roving_msgr_kit', 'roving_msgr_gyro_t1', 'swordmancer_dagger', 'swordmancer_kit', 'swordmancer_micro_filter', 'swordmancer_nav_beacon', 'turbid_cutting_torch_kit', 'type_50_yinglung_knife_kit', 'type_50_yinglung_knife_t1', 'type_50_yinglung_kit', 'type_50_yinglung_radar_t1', 'type_50_yinglung_radar_t2', 'xiranflow_baton', 'Æthertech_analysis_band_kit', 'Æthertech_stabilizer_kit', 'aethertech_stabilizer_t1', 'aethertech_watch');

commit;
