-- Normalized action timing storage.
-- Run once in the Supabase SQL editor. The migration is rerunnable.

begin;

alter table public.operator_skills add column if not exists duration_seconds numeric;
alter table public.operator_skills add column if not exists hit_timings numeric[] not null default '{}'::numeric[];
alter table public.operator_skills add column if not exists hit_timing_mode text not null default 'absolute';
alter table public.operator_skills add column if not exists effect_timings numeric[] not null default '{}'::numeric[];
alter table public.operator_skills add column if not exists form_key text not null default 'base';
alter table public.operator_skills add column if not exists variant_key text not null default 'base';

create table if not exists public.operator_basic_attack_sequences (
    id bigint generated by default as identity primary key,
    game text not null default 'arknights_endfield',
    operator_id integer not null references public.operators(id) on delete cascade,
    form_key text not null default 'base',
    attack_name text not null,
    sequence_index smallint not null,
    label text,
    kind text not null default 'normal',
    duration_seconds numeric not null check (duration_seconds > 0),
    cycle_duration_seconds numeric,
    hit_count smallint not null default 0 check (hit_count >= 0),
    hit_timings numeric[] not null default '{}'::numeric[],
    hit_timing_mode text not null default 'absolute',
    hit_multipliers numeric[] not null default '{}'::numeric[],
    atk_multiplier_total numeric not null default 0,
    stagger_multiplier numeric not null default 0,
    event_hit_index smallint,
    ends_cycle boolean not null default false,
    emits text[] not null default '{}'::text[],
    icon_path text,
    description text,
    verified boolean not null default false,
    source_url text,
    source_note text,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now(),
    unique (game, operator_id, form_key, sequence_index)
);

create index if not exists idx_operator_basic_attack_sequences_lookup
    on public.operator_basic_attack_sequences (game, operator_id, form_key, sequence_index);

create or replace function public.set_operator_basic_attack_sequence_updated_at()
returns trigger
language plpgsql
set search_path = public
as $$
begin
    new.updated_at = now();
    return new;
end;
$$;

drop trigger if exists operator_basic_attack_sequences_set_updated_at
    on public.operator_basic_attack_sequences;
create trigger operator_basic_attack_sequences_set_updated_at
    before update on public.operator_basic_attack_sequences
    for each row
    execute function public.set_operator_basic_attack_sequence_updated_at();

-- Copy the current base BATK payloads into normalized sequence rows.
with base_attacks as (
    select
        operator_row.id as operator_id,
        coalesce(operator_row.raw_data -> 'basicAttack', operator_row.raw_data -> 'basic_attack') as attack
    from public.operators as operator_row
    where coalesce(operator_row.raw_data -> 'basicAttack', operator_row.raw_data -> 'basic_attack') is not null
),
base_sequences as (
    select
        base_attacks.operator_id,
        base_attacks.attack,
        sequence.value as sequence,
        sequence.ordinality::smallint as ordinal
    from base_attacks
    cross join lateral jsonb_array_elements(coalesce(base_attacks.attack -> 'sequences', '[]'::jsonb))
        with ordinality as sequence(value, ordinality)
)
insert into public.operator_basic_attack_sequences (
    game, operator_id, form_key, attack_name, sequence_index, label, kind,
    duration_seconds, cycle_duration_seconds, hit_count, hit_timings, hit_timing_mode,
    hit_multipliers, atk_multiplier_total, stagger_multiplier, event_hit_index,
    ends_cycle, emits, icon_path, description, verified, source_note
)
select
    'arknights_endfield',
    base_sequences.operator_id,
    'base',
    coalesce(base_sequences.attack ->> 'name', 'Basic Attack'),
    coalesce(nullif(base_sequences.sequence ->> 'sequenceIndex', '')::smallint, base_sequences.ordinal),
    base_sequences.sequence ->> 'label',
    coalesce(base_sequences.sequence ->> 'kind', 'normal'),
    coalesce(
        nullif(base_sequences.sequence ->> 'duration', '')::numeric,
        nullif(base_sequences.sequence ->> 'durationSeconds', '')::numeric,
        nullif(base_sequences.sequence ->> 'sequenceDuration', '')::numeric
    ),
    coalesce(
        nullif(base_sequences.attack ->> 'cycleDuration', '')::numeric,
        nullif(base_sequences.attack ->> 'loopDuration', '')::numeric,
        nullif(base_sequences.attack ->> 'sequenceDuration', '')::numeric,
        nullif(base_sequences.attack ->> 'totalDuration', '')::numeric
    ),
    coalesce(
        nullif(base_sequences.sequence ->> 'hitCount', '')::smallint,
        jsonb_array_length(coalesce(base_sequences.sequence -> 'hitTimings', '[]'::jsonb))
    ),
    array(
        select timing.value::numeric
        from jsonb_array_elements_text(coalesce(base_sequences.sequence -> 'hitTimings', '[]'::jsonb))
            with ordinality as timing(value, ordinality)
        order by timing.ordinality
    ),
    coalesce(base_sequences.sequence ->> 'hitTimingMode', base_sequences.attack ->> 'hitTimingMode', 'absolute'),
    array(
        select multiplier.value::numeric
        from jsonb_array_elements_text(coalesce(base_sequences.sequence -> 'hitMultipliers', '[]'::jsonb))
            with ordinality as multiplier(value, ordinality)
        order by multiplier.ordinality
    ),
    coalesce(nullif(base_sequences.sequence ->> 'atkMultiplierTotal', '')::numeric, 0),
    coalesce(nullif(base_sequences.sequence ->> 'staggerMultiplier', '')::numeric, 0),
    nullif(base_sequences.sequence ->> 'eventHitIndex', '')::smallint,
    coalesce((base_sequences.sequence ->> 'endsCycle')::boolean, false),
    array(
        select emitted.value
        from jsonb_array_elements_text(coalesce(base_sequences.sequence -> 'emits', '[]'::jsonb))
            with ordinality as emitted(value, ordinality)
        order by emitted.ordinality
    ),
    coalesce(base_sequences.attack ->> 'iconSmall', base_sequences.attack ->> 'icon'),
    base_sequences.attack ->> 'description',
    coalesce(
        (base_sequences.attack ->> 'timingVerified')::boolean,
        (base_sequences.attack ->> 'verified')::boolean,
        false
    ),
    'Migrated from operators.raw_data.basicAttack'
from base_sequences
where coalesce(
    nullif(base_sequences.sequence ->> 'duration', '')::numeric,
    nullif(base_sequences.sequence ->> 'durationSeconds', '')::numeric,
    nullif(base_sequences.sequence ->> 'sequenceDuration', '')::numeric
) > 0
on conflict (game, operator_id, form_key, sequence_index) do nothing;

-- Copy form-specific BATKs, including Zhuang's Ultimate form.
with form_attacks as (
    select
        variant.operator_id,
        variant.form_key,
        variant.action_override as attack,
        variant.verified,
        variant.source_url,
        variant.source_note
    from public.operator_form_action_variants as variant
    where variant.game = 'arknights_endfield'
      and variant.action_key = 'basic_attack'
),
form_sequences as (
    select
        form_attacks.*,
        sequence.value as sequence,
        sequence.ordinality::smallint as ordinal
    from form_attacks
    cross join lateral jsonb_array_elements(coalesce(form_attacks.attack -> 'sequences', '[]'::jsonb))
        with ordinality as sequence(value, ordinality)
)
insert into public.operator_basic_attack_sequences (
    game, operator_id, form_key, attack_name, sequence_index, label, kind,
    duration_seconds, cycle_duration_seconds, hit_count, hit_timings, hit_timing_mode,
    hit_multipliers, atk_multiplier_total, stagger_multiplier, event_hit_index,
    ends_cycle, emits, icon_path, description, verified, source_url, source_note
)
select
    'arknights_endfield',
    form_sequences.operator_id,
    form_sequences.form_key,
    coalesce(form_sequences.attack ->> 'name', 'Basic Attack'),
    coalesce(nullif(form_sequences.sequence ->> 'sequenceIndex', '')::smallint, form_sequences.ordinal),
    form_sequences.sequence ->> 'label',
    coalesce(form_sequences.sequence ->> 'kind', 'normal'),
    coalesce(
        nullif(form_sequences.sequence ->> 'duration', '')::numeric,
        nullif(form_sequences.sequence ->> 'durationSeconds', '')::numeric,
        nullif(form_sequences.sequence ->> 'sequenceDuration', '')::numeric
    ),
    coalesce(
        nullif(form_sequences.attack ->> 'cycleDuration', '')::numeric,
        nullif(form_sequences.attack ->> 'loopDuration', '')::numeric,
        nullif(form_sequences.attack ->> 'sequenceDuration', '')::numeric,
        nullif(form_sequences.attack ->> 'totalDuration', '')::numeric
    ),
    coalesce(
        nullif(form_sequences.sequence ->> 'hitCount', '')::smallint,
        jsonb_array_length(coalesce(form_sequences.sequence -> 'hitTimings', '[]'::jsonb))
    ),
    array(
        select timing.value::numeric
        from jsonb_array_elements_text(coalesce(form_sequences.sequence -> 'hitTimings', '[]'::jsonb))
            with ordinality as timing(value, ordinality)
        order by timing.ordinality
    ),
    coalesce(form_sequences.sequence ->> 'hitTimingMode', form_sequences.attack ->> 'hitTimingMode', 'absolute'),
    array(
        select multiplier.value::numeric
        from jsonb_array_elements_text(coalesce(form_sequences.sequence -> 'hitMultipliers', '[]'::jsonb))
            with ordinality as multiplier(value, ordinality)
        order by multiplier.ordinality
    ),
    coalesce(nullif(form_sequences.sequence ->> 'atkMultiplierTotal', '')::numeric, 0),
    coalesce(nullif(form_sequences.sequence ->> 'staggerMultiplier', '')::numeric, 0),
    nullif(form_sequences.sequence ->> 'eventHitIndex', '')::smallint,
    coalesce((form_sequences.sequence ->> 'endsCycle')::boolean, false),
    array(
        select emitted.value
        from jsonb_array_elements_text(coalesce(form_sequences.sequence -> 'emits', '[]'::jsonb))
            with ordinality as emitted(value, ordinality)
        order by emitted.ordinality
    ),
    coalesce(form_sequences.attack ->> 'iconSmall', form_sequences.attack ->> 'icon'),
    form_sequences.attack ->> 'description',
    coalesce(
        (form_sequences.attack ->> 'timingVerified')::boolean,
        (form_sequences.attack ->> 'verified')::boolean,
        form_sequences.verified,
        false
    ),
    form_sequences.source_url,
    coalesce(form_sequences.source_note, 'Migrated from operator_form_action_variants.action_override')
from form_sequences
where coalesce(
    nullif(form_sequences.sequence ->> 'duration', '')::numeric,
    nullif(form_sequences.sequence ->> 'durationSeconds', '')::numeric,
    nullif(form_sequences.sequence ->> 'sequenceDuration', '')::numeric
) > 0
on conflict (game, operator_id, form_key, sequence_index) do nothing;

-- Move timing values already present in skill raw_data into first-class columns.
update public.operator_skills
set
    duration_seconds = coalesce(
        duration_seconds,
        nullif(raw_data ->> 'actionDurationSeconds', '')::numeric,
        nullif(raw_data ->> 'castDurationSeconds', '')::numeric
    ),
    hit_timings = case
        when cardinality(hit_timings) > 0 then hit_timings
        when jsonb_typeof(raw_data -> 'hitTimings') = 'array' then array(
            select value::numeric from jsonb_array_elements_text(raw_data -> 'hitTimings')
        )
        else '{}'::numeric[]
    end,
    hit_timing_mode = coalesce(nullif(raw_data ->> 'hitTimingMode', ''), hit_timing_mode, 'absolute'),
    effect_timings = case
        when cardinality(effect_timings) > 0 then effect_timings
        when jsonb_typeof(raw_data -> 'effectTimings') = 'array' then array(
            select value::numeric from jsonb_array_elements_text(raw_data -> 'effectTimings')
        )
        when (raw_data #>> '{delayedFollowUp,delaySeconds}') ~ '^[0-9]+(\.[0-9]+)?$'
            then array[(raw_data #>> '{delayedFollowUp,delaySeconds}')::numeric]
        when (raw_data #>> '{manualSequence,automaticDelaySeconds}') ~ '^[0-9]+(\.[0-9]+)?$'
            then array[(raw_data #>> '{manualSequence,automaticDelaySeconds}')::numeric]
        else '{}'::numeric[]
    end,
    form_key = coalesce(nullif(raw_data ->> 'formKey', ''), form_key, 'base'),
    variant_key = coalesce(nullif(raw_data ->> 'variantKey', ''), variant_key, 'base');

alter table public.operator_basic_attack_sequences enable row level security;
drop policy if exists "Public read operator basic attack sequences" on public.operator_basic_attack_sequences;
create policy "Public read operator basic attack sequences"
    on public.operator_basic_attack_sequences
    for select
    using (true);

commit;

-- Verification:
-- select operator_id, form_key, attack_name, sequence_index, duration_seconds, hit_timings
-- from public.operator_basic_attack_sequences
-- order by operator_id, form_key, sequence_index;
