-- Generic timeline-aware operator forms and Zhuang Fangyi's Empyrean of Truth.
-- Values and conditions live in Supabase; the client only resolves generic form/action rows.

begin;

create table if not exists public.operator_forms (
    id bigint generated by default as identity primary key,
    game text not null default 'arknights_endfield',
    form_key text not null,
    operator_id integer not null references public.operators(id) on delete cascade,
    name text not null,
    activation_skill_id integer not null references public.operator_skills(id) on delete cascade,
    duration_seconds numeric not null,
    priority integer not null default 0,
    icon_path text,
    visible boolean not null default true,
    enabled boolean not null default true,
    verified boolean not null default false,
    source_url text,
    source_note text,
    raw_data jsonb not null default '{}'::jsonb,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now(),
    constraint operator_forms_unique_key unique (game, operator_id, form_key),
    constraint operator_forms_positive_duration check (duration_seconds > 0),
    constraint operator_forms_raw_data_object check (jsonb_typeof(raw_data) = 'object')
);

create index if not exists idx_operator_forms_activation
    on public.operator_forms (game, activation_skill_id, enabled);

create table if not exists public.operator_form_action_variants (
    id bigint generated by default as identity primary key,
    game text not null default 'arknights_endfield',
    form_key text not null,
    operator_id integer not null references public.operators(id) on delete cascade,
    action_key text not null,
    action_override jsonb not null default '{}'::jsonb,
    priority integer not null default 0,
    enabled boolean not null default true,
    verified boolean not null default false,
    source_url text,
    source_note text,
    raw_data jsonb not null default '{}'::jsonb,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now(),
    constraint operator_form_action_variants_unique_key unique (game, operator_id, form_key, action_key),
    constraint operator_form_action_variants_override_object check (jsonb_typeof(action_override) = 'object'),
    constraint operator_form_action_variants_raw_data_object check (jsonb_typeof(raw_data) = 'object'),
    constraint operator_form_action_variants_form_fk
        foreign key (game, operator_id, form_key)
        references public.operator_forms(game, operator_id, form_key)
        on delete cascade
);

create index if not exists idx_operator_form_variants_lookup
    on public.operator_form_action_variants (game, operator_id, form_key, action_key, enabled, priority);

alter table public.operator_forms enable row level security;
alter table public.operator_form_action_variants enable row level security;

drop policy if exists "Public read operator forms" on public.operator_forms;
create policy "Public read operator forms"
    on public.operator_forms for select
    using (enabled = true);

drop policy if exists "Public read operator form action variants" on public.operator_form_action_variants;
create policy "Public read operator form action variants"
    on public.operator_form_action_variants for select
    using (enabled = true);

insert into public.operator_forms (
    game, form_key, operator_id, name, activation_skill_id, duration_seconds,
    priority, icon_path, visible, enabled, verified, source_url, source_note, raw_data
)
values (
    'arknights_endfield',
    'empyrean_of_truth',
    9,
    'Empyrean of Truth',
    904,
    25,
    100,
    'assets/operators/skills/zhuang/ult_small.png',
    true,
    true,
    true,
    'https://end.wiki/en/characters/chr-0030-zhuangfy/skills/',
    'Smiting Tempest skill table: 25 second duration; checked 2026-07-18.',
    '{"activationMode":"skill_cast","recastMode":"refresh","displayTrack":"buff"}'::jsonb
)
on conflict (game, operator_id, form_key) do update set
    name = excluded.name,
    activation_skill_id = excluded.activation_skill_id,
    duration_seconds = excluded.duration_seconds,
    priority = excluded.priority,
    icon_path = excluded.icon_path,
    visible = excluded.visible,
    enabled = excluded.enabled,
    verified = excluded.verified,
    source_url = excluded.source_url,
    source_note = excluded.source_note,
    raw_data = excluded.raw_data,
    updated_at = now();

-- Upgrade the base BATK from five anonymous hits to five damage-bearing sequences.
-- Existing observed hit times are retained; multiplier values are Level 12 combat-table values.
update public.operators
set raw_data = jsonb_set(
        raw_data,
        '{basicAttack}',
        '{
          "name":"Jolting Arts",
          "hitCount":13,
          "finalHitCount":1,
          "secondsPerSlot":1,
          "cycleDuration":4.817,
          "hitTimingMode":"intervals",
          "timingVerified":true,
          "damageVerified":true,
          "finisherAtkMultiplier":9.0,
          "diveAtkMultiplier":1.8,
          "sourceUrl":"https://endfield.wiki.gg/wiki/Zhuang_Fangyi",
          "sourceNote":"User-supplied frame timings; SEQ 1 second hit interval corrected to 0.083 on 2026-07-19.",
          "sequences":[
            {"sequenceIndex":1,"label":"SEQ 1","kind":"normal","duration":0.667,"hitCount":2,"hitTimings":[0.3,0.083],"atkMultiplierTotal":0.36},
            {"sequenceIndex":2,"label":"SEQ 2","kind":"normal","duration":1.367,"hitCount":5,"hitTimings":[0.45,0.317,0.05,0.05,0.083],"atkMultiplierTotal":0.54},
            {"sequenceIndex":3,"label":"SEQ 3","kind":"normal","duration":0.617,"hitCount":2,"hitTimings":[0.367,0.067],"atkMultiplierTotal":0.72},
            {"sequenceIndex":4,"label":"SEQ 4","kind":"normal","duration":0.583,"hitCount":3,"hitTimings":[0.117,0.117,0.083],"atkMultiplierTotal":1.01},
            {"sequenceIndex":5,"label":"FS","kind":"final_strike","duration":1.583,"hitCount":1,"hitTimings":[0.267],"endsCycle":true,"staggerMultiplier":1.8,"atkMultiplierTotal":1.08,"emits":["final_strike"]}
          ]
        }'::jsonb,
        true
    ),
    updated_at = now()
where id = 9 and game = 'arknights_endfield';

-- Level 12 core kit. Sunderblades are described entirely by generic resource
-- data so the client does not need Zhuang- or skill-specific branches.
update public.operator_skills
set raw_data = coalesce(raw_data, '{}'::jsonb) || '{
  "damageMultiplier":45,
  "damageProfile":{"atkMultiplier":0.45,"flatDamage":0,"hitCount":1,"element":"electric","verified":true,"sourceUrl":"https://www.icy-veins.com/arknights-endfield/zhuang-fangyi-profile-skills","canCrit":true},
  "consumeDebuffs":["electrification"],
  "ultimateEnergyGain":6,
  "battlefieldResource":{
    "resourceKey":"sunderblades",
    "name":"Sunderblades",
    "ownerOperatorId":9,
    "maxStacks":9,
    "durationSeconds":36,
    "creation":{"consumedEffect":"electrification","baseStacks":1,"stacksPerConsumedStack":1,"maxStacksPerUse":3,"fallbackStacks":1,"fallbackWhenBelowStacks":3},
    "strikes":{"useAllActiveStacks":true,"atkMultiplierPerStrike":0.45,"bonusAtkMultiplierPerConsumedStack":0.09,"finalStrikeMultiplier":6},
    "ultimateEnergyPerStrike":6,
    "progressiveBuff":{"effect":"electric_amp","baseValue":18,"valuePerStrike":2,"valueField":"electricDamageBonusPercent","durationSeconds":5,"target":"self"}
  },
  "buffs":[{"id":"electric_amp","name":"Electric Amp","appliesEffect":"electric_amp","persistsForCombo":true,"visible":true,"stackable":false,"durationSeconds":5,"target":"self","electricDamageBonusPercent":18}]
}'::jsonb,
    updated_at = now()
where operator_id = 9 and id = 902;

update public.operator_skills
set raw_data = coalesce(raw_data, '{}'::jsonb) || '{
  "damageMultiplier":360,
  "damageProfile":{"atkMultiplier":3.6,"flatDamage":0,"hitCount":1,"element":"electric","verified":true,"sourceUrl":"https://www.icy-veins.com/arknights-endfield/zhuang-fangyi-profile-skills","canCrit":true},
  "ultimateEnergyGain":20,
  "consumeDebuffs":["electric_infliction"],
  "consumedEffectScaling":{"effect":"electric_infliction","ultimateEnergyBase":10,"ultimateEnergyPerStack":10,"effectValues":[{"effect":"electrification","stacksAppliedPerStack":1,"stacksAppliedWhenExisting":1,"minimumStacksApplied":1,"maxStacks":4}]},
  "debuffs":[{"id":"electrification","name":"Electrification","appliesEffect":"electrification","persistsForCombo":true,"visible":true,"stackable":true,"stacksApplied":1,"maxStacks":4}]
}'::jsonb,
    updated_at = now()
where operator_id = 9 and id = 903;

insert into public.operator_form_action_variants (
    game, form_key, operator_id, action_key, action_override, priority,
    enabled, verified, source_url, source_note, raw_data
)
values
    (
        'arknights_endfield', 'empyrean_of_truth', 9, 'basic_attack',
        '{
          "name":"Jolting Arts · Empyrean of Truth",
          "description":"Enhanced three-sequence Electric Basic Attack while Empyrean of Truth is active.",
          "hitTimingMode":"absolute",
          "hitCount":3,
          "finalHitCount":1,
          "cycleDuration":3.0,
          "timingVerified":false,
          "damageVerified":true,
          "sequences":[
            {"sequenceIndex":1,"label":"SEQ 1","kind":"normal","hitCount":1,"hitTimings":[0.6],"duration":0.8,"atkMultiplierTotal":1.5},
            {"sequenceIndex":2,"label":"SEQ 2","kind":"normal","hitCount":1,"hitTimings":[0.75],"duration":1.0,"atkMultiplierTotal":2.1},
            {"sequenceIndex":3,"label":"FS","kind":"final_strike","hitCount":1,"hitTimings":[1.0],"duration":1.2,"atkMultiplierTotal":3.0,"emits":["final_strike"]}
          ]
        }'::jsonb,
        100, true, true,
        'https://end.wiki/en/characters/chr-0030-zhuangfy/skills/',
        'Level 12 BATK multipliers are verified. Exact animation hit timing is an explicit unverified simulator estimate.',
        '{"rangeEnhanced":true,"interruptResistanceEnhanced":true}'::jsonb
    ),
    (
        'arknights_endfield', 'empyrean_of_truth', 9, 'skill:902',
        '{
          "name":"Mantra of Sundering · Empyrean of Truth",
          "description":"Enhanced Thunder Strikes. The final Thunder Strike applies Electric Infliction. The first cast in each transformation is free, consumes no Electrification, and guarantees 3 Sunderblades.",
          "damageMultiplier":81,
          "damageProfile":{"atkMultiplier":0.81,"flatDamage":0,"hitCount":1,"element":"electric","verified":true,"sourceUrl":"https://www.icy-veins.com/arknights-endfield/zhuang-fangyi-profile-skills","canCrit":true},
          "battlefieldResource":{"strikes":{"atkMultiplierPerStrike":0.81,"bonusAtkMultiplierPerConsumedStack":0.18}},
          "debuffs":[{"id":"electric_infliction","name":"Electric Infliction","appliesEffect":"electric_infliction","visible":true,"stackable":true,"persistsForCombo":true}],
          "rangeEnhanced":true,
          "finalThunderStrikeApplies":"electric_infliction",
          "firstUsePerActivation":{"sp_cost":0,"spCost":0,"energy":0,"consumeDebuffs":[],"battlefieldResource":{"creation":{"guaranteedStacks":3}},"freeFormCast":true}
        }'::jsonb,
        100, true, true,
        'https://endfield.wiki.gg/wiki/Zhuang_Fangyi',
        'Level 12 Ultimate Thunder Strike multiplier and form behavior.',
        '{}'::jsonb
    ),
    (
        'arknights_endfield', 'empyrean_of_truth', 9, 'skill:903',
        '{
          "name":"Breath of Transformation · Empyrean of Truth",
          "description":"Enhanced area Combo Skill with 4x cooldown recovery while Empyrean of Truth is active.",
          "cooldown":4.25,
          "cooldownRateMultiplier":4,
          "areaOfEffect":true,
          "damageMultiplier":540,
          "damageProfile":{"atkMultiplier":5.4,"flatDamage":0,"hitCount":1,"element":"electric","verified":true,"sourceUrl":"https://www.icy-veins.com/arknights-endfield/zhuang-fangyi-profile-skills","canCrit":true}
        }'::jsonb,
        100, true, true,
        'https://endfield.wiki.gg/wiki/Zhuang_Fangyi',
        'Level 12 Ultimate multiplier; cooldown recovery becomes 4x faster.',
        '{}'::jsonb
    )
on conflict (game, operator_id, form_key, action_key) do update set
    action_override = excluded.action_override,
    priority = excluded.priority,
    enabled = excluded.enabled,
    verified = excluded.verified,
    source_url = excluded.source_url,
    source_note = excluded.source_note,
    raw_data = excluded.raw_data,
    updated_at = now();

commit;

-- Verification:
-- select f.name, f.duration_seconds, v.action_key, v.action_override
-- from public.operator_forms f
-- join public.operator_form_action_variants v
--   on v.game = f.game and v.operator_id = f.operator_id and v.form_key = f.form_key
-- where f.operator_id = 9
-- order by v.action_key;
