begin;

-- Operator mechanics audit, batch 07A: generic talents and potentials.
-- Operator names, triggers, conditions, formulae and values live only here.
create table if not exists public.operator_passive_rules (
    id bigint generated by default as identity primary key,
    game text not null default 'arknights_endfield',
    rule_key text not null,
    operator_id bigint not null references public.operators(id) on delete cascade,
    name text not null,
    rule_type text not null default 'talent' check (rule_type in ('talent', 'potential')),
    resolution_type text not null check (resolution_type in ('action_modifier', 'triggered_effect')),
    minimum_potential integer not null default 0 check (minimum_potential between 0 and 5),
    conditions jsonb not null default '{}'::jsonb,
    trigger jsonb not null default '{}'::jsonb,
    effect jsonb not null default '{}'::jsonb,
    cooldown_seconds numeric not null default 0,
    priority integer not null default 100,
    enabled boolean not null default true,
    verified boolean not null default false,
    source_url text,
    source_note text,
    raw_data jsonb not null default '{}'::jsonb,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now(),
    unique (game, rule_key)
);

alter table public.operator_passive_rules enable row level security;
drop policy if exists "operator_passive_rules_public_read" on public.operator_passive_rules;
create policy "operator_passive_rules_public_read"
on public.operator_passive_rules for select
using (enabled = true);
grant select on public.operator_passive_rules to anon, authenticated;

insert into public.operator_passive_rules (
    game, rule_key, operator_id, name, rule_type, resolution_type,
    minimum_potential, conditions, trigger, effect, cooldown_seconds,
    priority, enabled, verified, source_url, source_note
) values
(
    'arknights_endfield',
    'akekuri_cheer_of_victory_lv2',
    2,
    'Cheer of Victory',
    'talent',
    'action_modifier',
    0,
    '{"skillIds":[203]}'::jsonb,
    '{}'::jsonb,
    '{"spRecoveryStatScaling":{"stat":"intellect","perPoints":10,"percentPerStep":1.5,"maxPercent":75,"rounding":"floor"}}'::jsonb,
    0,
    10,
    true,
    true,
    'https://www.icy-veins.com/arknights-endfield/akekuri-profile-skills',
    'Talent level 2: every 10 Intellect increases Flash and Dash SP recovery by 1.5%, capped at 75%.'
),
(
    'arknights_endfield',
    'ember_pay_the_ferric_price_lv2',
    17,
    'Pay the Ferric Price',
    'talent',
    'triggered_effect',
    0,
    '{}'::jsonb,
    '{"effects":["operator_attacked"],"controlledOperatorOnly":true}'::jsonb,
    '{"actionOverride":{"damageProfile":null,"buffs":[{"id":"ember_pay_the_ferric_price","name":"Pay the Ferric Price","appliesEffect":"ember_pay_the_ferric_price","target":"self","visible":true,"stackable":true,"stacksApplied":1,"maxStacks":3,"durationSeconds":7,"atkPercent":9,"verified":true,"sourceUrl":"https://www.icy-veins.com/arknights-endfield/ember-profile-skills"}]}}'::jsonb,
    0,
    20,
    true,
    true,
    'https://www.icy-veins.com/arknights-endfield/ember-profile-skills',
    'Talent level 2: after Ember receives enemy damage, +9% ATK for 7 seconds, up to 3 stacks.'
),
(
    'arknights_endfield',
    'akekuri_positive_feedback_p1',
    2,
    'Positive Feedback',
    'potential',
    'triggered_effect',
    1,
    '{}'::jsonb,
    '{"effects":["sp_recovery"],"sourceOperatorOnly":true}'::jsonb,
    '{"actionOverride":{"damageProfile":null,"buffs":[{"id":"akekuri_positive_feedback","name":"Positive Feedback","appliesEffect":"akekuri_positive_feedback","target":"self","visible":true,"stackable":true,"stacksApplied":1,"maxStacks":5,"durationSeconds":10,"atkPercent":10,"verified":true,"sourceUrl":"https://www.icy-veins.com/arknights-endfield/akekuri-profile-skills"}]}}'::jsonb,
    0,
    30,
    true,
    true,
    'https://www.icy-veins.com/arknights-endfield/akekuri-profile-skills',
    'Potential 1: after Akekuri recovers SP with a skill, +10% ATK for 10 seconds, up to 5 stacks. The resolver gates this at operator Potential 1.'
)
on conflict (game, rule_key) do update set
    operator_id = excluded.operator_id,
    name = excluded.name,
    rule_type = excluded.rule_type,
    resolution_type = excluded.resolution_type,
    minimum_potential = excluded.minimum_potential,
    conditions = excluded.conditions,
    trigger = excluded.trigger,
    effect = excluded.effect,
    cooldown_seconds = excluded.cooldown_seconds,
    priority = excluded.priority,
    enabled = excluded.enabled,
    verified = excluded.verified,
    source_url = excluded.source_url,
    source_note = excluded.source_note,
    updated_at = now();

commit;

select rule_key, operator_id, rule_type, resolution_type, minimum_potential, verified
from public.operator_passive_rules
where game = 'arknights_endfield'
order by priority, rule_key;
