function getShortSkillType(type){const value=(type||"").toLowerCase();if(value.includes("final")||value==="fs")return"FS";if(value.includes("battle")||value==="bs")return"BS";if(value.includes("combo")||value==="cs")return"CS";if(value.includes("ultimate")||value==="ult")return"Ult";return type||"";}
function getVisibleRotationDebuffs(skillData){return(skillData?.debuffs||[]).filter(x=>x.visible!==false);}function getVisibleRotationBuffs(skillData){return(skillData?.buffs||[]).filter(x=>x.visible!==false);}function getRotationDebuffKey(effect){return normalizeDebuffKey({id:effect?.appliesEffect||effect?.id||effect?.name});}
function clearOtherExclusiveInflictions(activeKey,stackState,metaState){if(!EXCLUSIVE_INFLICTIONS.has(activeKey))return;EXCLUSIVE_INFLICTIONS.forEach(key=>{if(key===activeKey)return;delete stackState[key];delete metaState[key];});}
function addDebuffToRotationState(effect,stackState,metaState){const key=getRotationDebuffKey(effect);if(!key)return;clearOtherExclusiveInflictions(key,stackState,metaState);const registryEntry=DEBUFF_REGISTRY?.[key];const isStackable=effect?.stackable===true||registryEntry?.stackable===true;const maxStacks=Number(effect?.maxStacks||registryEntry?.maxStacks||4);const stacksApplied=Number(effect?.stacksApplied||effect?.stackCount||1);const safeMax=Number.isFinite(maxStacks)?maxStacks:4;const safeApplied=Number.isFinite(stacksApplied)?stacksApplied:1;if(isStackable){stackState[key]=Math.max(1,Math.min((stackState[key]||0)+safeApplied,safeMax));}else{stackState[key]=1;}metaState[key]={...effect,id:key,appliesEffect:key,stackable:isStackable,maxStacks:safeMax};}
function applyMatchingInflictionToRotationState(skillData,stackState,metaState){const config=skillData?.matchingInfliction;if(!config||!Array.isArray(config.candidateEffects))return;const minStacks=Number(config.minStacks||1);const matchingEffect=config.candidateEffects.find(effectName=>(stackState[normalizeDebuffKey({id:effectName})]||0)>=minStacks);if(!matchingEffect)return;addDebuffToRotationState({id:matchingEffect,name:matchingEffect,appliesEffect:matchingEffect,persistsForCombo:true,visible:true,stackable:true,stacksApplied:Number(config.stacksApplied||1),maxStacks:Number(config.maxStacks||4)},stackState,metaState);}
function consumeAllDebuffStacks(effectName,stackState,metaState){const key=normalizeDebuffKey({id:effectName});if(!key)return;delete stackState[key];delete metaState[key];}
function resolveRotationArtsReactionsWithFullConsume(stackState,metaState){if(!Array.isArray(ARTS_REACTIONS))return;let didResolve=true;let safetyCounter=0;const MAX_REACTION_LOOPS=20;while(didResolve&&safetyCounter<MAX_REACTION_LOOPS){didResolve=false;safetyCounter++;for(const reaction of ARTS_REACTIONS){const canResolve=reaction.requires.every(effectName=>(stackState[normalizeDebuffKey({id:effectName})]||0)>0);if(!canResolve)continue;reaction.requires.forEach(effectName=>consumeAllDebuffStacks(effectName,stackState,metaState));didResolve=true;}}}
function getActiveDebuffsFromRotationState(stackState,metaState){return Object.entries(stackState).filter(([,amount])=>amount>0).map(([key,amount])=>({...metaState[key],id:key,appliesEffect:key,stackCount:amount,currentStacks:amount,stacks:amount}));}
function applySkillDebuffsAndGetActiveState(skillData,stackState,metaState){getVisibleRotationDebuffs(skillData).forEach(effect=>{if(effect.persistsForCombo===false)return;addDebuffToRotationState(effect,stackState,metaState);});applyMatchingInflictionToRotationState(skillData,stackState,metaState);resolveRotationArtsReactionsWithFullConsume(stackState,metaState);return getActiveDebuffsFromRotationState(stackState,metaState);}
"+document.body.innerHTML.split('<script src="js/ui/rotationGrid.js"></script>')[0]