const fs = require("fs");
const path = require("path");
const vm = require("vm");

const rootDir = path.resolve(__dirname, "..");
const operatorsDir = path.join(rootDir, "js", "data", "operators");
const outputDir = path.join(rootDir, "supabase");
const seedPath = path.join(outputDir, "seed_operators.sql");
const jsonPath = path.join(outputDir, "operators.json");
const shouldPrintSql = process.argv.includes("--stdout");
const shouldPrintJson = process.argv.includes("--json");

const operatorFiles = [
    "ardelia.js",
    "antal.js",
    "alesh.js",
    "chen.js",
    "catcher.js",
    "dapan.js",
    "ember.js",
    "estella.js",
    "fluorite.js",
    "lastrite.js",
    "lifeng.js",
    "snowshine.js",
    "wulfgard.js",
    "xaihi.js",
    "pogranichnik.js",
    "zhuang.js",
    "avywenna.js",
    "arclight.js",
    "laevatain.js",
    "akekuri.js",
    "endministrator.js",
    "perlica.js",
    "rossi.js",
    "tangtang.js",
    "gilberta.js",
    "yvonne.js"
];

function readSource() {
    const pieces = operatorFiles.map(file => fs.readFileSync(path.join(operatorsDir, file), "utf8"));
    pieces.push(fs.readFileSync(path.join(rootDir, "js", "data", "operators.js"), "utf8"));
    pieces.push("operators;");
    return pieces.join("\n\n");
}

function slugify(value) {
    return String(value)
        .trim()
        .toLowerCase()
        .replace(/[^a-z0-9]+/g, "_")
        .replace(/^_+|_+$/g, "");
}

function sqlString(value) {
    if (value === null || value === undefined) return "null";
    return `'${String(value).replace(/'/g, "''")}'`;
}

function sqlNumber(value) {
    return Number.isFinite(Number(value)) ? String(Number(value)) : "null";
}

function sqlBoolean(value) {
    return value === true ? "true" : "false";
}

function sqlJson(value) {
    return `${sqlString(JSON.stringify(value ?? {}))}::jsonb`;
}

function toOperatorRaw(operator) {
    const { skills, ...raw } = operator;
    return raw;
}

function toSkillRaw(skill) {
    return { ...skill };
}

function buildOperatorRows(operators) {
    return operators.map((operator, index) => {
        const values = [
            sqlNumber(operator.id),
            sqlString("arknights_endfield"),
            sqlString(slugify(operator.name)),
            sqlString(operator.name),
            sqlNumber(operator.star),
            sqlString(operator.operatorClass),
            sqlString(operator.elementType || "neutral"),
            sqlString(operator.icon),
            sqlBoolean(operator.canEnterUltimateState),
            sqlNumber(index + 1),
            sqlJson(toOperatorRaw(operator))
        ];

        return `(${values.join(", ")})`;
    });
}

function buildSkillRows(operators) {
    const rows = [];

    operators.forEach(operator => {
        (operator.skills || []).forEach((skill, index) => {
            const values = [
                sqlNumber(skill.id),
                sqlNumber(operator.id),
                sqlNumber(index + 1),
                sqlString(skill.name),
                sqlString(skill.type),
                sqlString(skill.shortType || null),
                sqlNumber(skill.cooldown),
                sqlNumber(skill.energy),
                sqlString(skill.elementType || operator.elementType || "neutral"),
                sqlString(skill.icon || operator.icon),
                sqlString(skill.iconSmall || null),
                sqlString(skill.description || null),
                sqlString(skill.comboTrigger || null),
                sqlString(skill.comboTriggerMode || null),
                sqlJson(toSkillRaw(skill))
            ];

            rows.push(`(${values.join(", ")})`);
        });
    });

    return rows;
}

function buildSeedSql(operators) {
    const operatorRows = buildOperatorRows(operators);
    const skillRows = buildSkillRows(operators);

    return `-- Generated by tools/exportOperatorsForSupabase.js
-- Run supabase/schema.sql before this file.

begin;

insert into public.operators (
    id,
    game,
    slug,
    name,
    star,
    operator_class,
    element_type,
    icon_path,
    can_enter_ultimate_state,
    sort_order,
    raw_data
) values
${operatorRows.join(",\n")}
on conflict (id) do update set
    game = excluded.game,
    slug = excluded.slug,
    name = excluded.name,
    star = excluded.star,
    operator_class = excluded.operator_class,
    element_type = excluded.element_type,
    icon_path = excluded.icon_path,
    can_enter_ultimate_state = excluded.can_enter_ultimate_state,
    sort_order = excluded.sort_order,
    raw_data = excluded.raw_data,
    updated_at = now();

insert into public.operator_skills (
    id,
    operator_id,
    slot_index,
    name,
    skill_type,
    short_type,
    cooldown,
    energy,
    element_type,
    icon_path,
    icon_small_path,
    description,
    combo_trigger,
    combo_trigger_mode,
    raw_data
) values
${skillRows.join(",\n")}
on conflict (id) do update set
    operator_id = excluded.operator_id,
    slot_index = excluded.slot_index,
    name = excluded.name,
    skill_type = excluded.skill_type,
    short_type = excluded.short_type,
    cooldown = excluded.cooldown,
    energy = excluded.energy,
    element_type = excluded.element_type,
    icon_path = excluded.icon_path,
    icon_small_path = excluded.icon_small_path,
    description = excluded.description,
    combo_trigger = excluded.combo_trigger,
    combo_trigger_mode = excluded.combo_trigger_mode,
    raw_data = excluded.raw_data,
    updated_at = now();

commit;
`;
}

const context = vm.createContext({});
const operators = vm.runInContext(readSource(), context);

if (!Array.isArray(operators)) {
    throw new Error("Could not read operators array.");
}

const missingMeta = operators.filter(operator => !operator.star || !operator.operatorClass);
if (missingMeta.length) {
    throw new Error(`Missing star/operatorClass: ${missingMeta.map(operator => operator.name).join(", ")}`);
}

fs.mkdirSync(outputDir, { recursive: true });
const jsonOutput = `${JSON.stringify(operators, null, 2)}\n`;
const sqlOutput = buildSeedSql(operators);

if (shouldPrintJson) {
    process.stdout.write(jsonOutput);
} else if (shouldPrintSql) {
    process.stdout.write(sqlOutput);
} else {
    fs.writeFileSync(jsonPath, jsonOutput, "utf8");
    fs.writeFileSync(seedPath, sqlOutput, "utf8");

    console.log(`Exported ${operators.length} operators to ${seedPath}`);
    console.log(`Exported JSON snapshot to ${jsonPath}`);
}
